# Building a Neural Network Regression Model in Keras

By Jaime Hernandez

### Introduction

This notebook experiments with the implementation of regression model using the deep learning Keras library.  Performance of the model is evaluated with an increasing the number of training epochs and changing number of hidden layers. For this analysis, concrete strength will be predicted using this dataset: https://cocl.us/concrete_data.

### Load Libraries

In [25]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import keras
from keras.models import Sequential
from keras.layers import Dense

### Read Data and Gain Understanding of Dataset

In [7]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
print("Shape:")
print(concrete_data.shape)
concrete_data.head()

Shape:
(1030, 9)


Cement  Blast Furnace Slag  Fly Ash  Water  Superplasticizer  \
0   540.0                 0.0      0.0  162.0               2.5   
1   540.0                 0.0      0.0  162.0               2.5   
2   332.5               142.5      0.0  228.0               0.0   
3   332.5               142.5      0.0  228.0               0.0   
4   198.6               132.4      0.0  192.0               0.0   

   Coarse Aggregate  Fine Aggregate  Age  Strength  
0            1040.0           676.0   28     79.99  
1            1055.0           676.0   28     61.89  
2             932.0           594.0  270     40.27  
3             932.0           594.0  365     41.05  
4             978.4           825.5  360     44.30

In [12]:
#Check for nulls
print(concrete_data.isnull().sum())


Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64


### Prepare Data For Model - Split into Predictors and Target

In [15]:
concrete_data_columns = concrete_data.columns

predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [17]:
n_cols = predictors_norm.shape[1] # number of predictors

### Building Neural Network Model

One hidden layer of 10 nodes and a ReLU activation function will be used.

In [14]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

### Fit Model and Evaluate

A) Fit using 50 Epochs, 50 separete times using different random train-test samples with a 70:30 split.

In [33]:
#Establish parameters
EPochs = 50
samples = 50

In [40]:
#Predict and evaluate

#Starting list that will contain RMSE scores for each sample
eval_list = []

for i in range(samples):
    print("Sample " + str(i))
    #Split data into test and train over each iteration
    X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=.3, random_state=99)

    #Re-build NN
    model = regression_model()
    
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=EPochs, verbose=1)
    eval_list.append(model.evaluate(X_test, y_test, verbose=0))

    

Sample 0
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 652us/step - loss: 4278.5931 - val_loss: 733.3927
Epoch 2/50
721/721 [==============================] - 0s 59us/step - loss: 817.6087 - val_loss: 624.5573
Epoch 3/50
721/721 [==============================] - 0s 57us/step - loss: 627.0673 - val_loss: 564.0087
Epoch 4/50
721/721 [==============================] - 0s 61us/step - loss: 530.8896 - val_loss: 462.2496
Epoch 5/50
721/721 [==============================] - 0s 57us/step - loss: 452.8064 - val_loss: 404.4518
Epoch 6/50
721/721 [==============================] - 0s 57us/step - loss: 392.3975 - val_loss: 364.5648
Epoch 7/50
721/721 [==============================] - 0s 58us/step - loss: 348.1200 - val_loss: 316.6880
Epoch 8/50
721/721 [==============================] - 0s 59us/step - loss: 314.0529 - val_loss: 300.1630
Epoch 9/50
721/721 [==============================] - 0s 65us/step - loss: 286.5266 - val_loss: 263.293

721/721 [==============================] - 0s 56us/step - loss: 293.8766 - val_loss: 296.6510
Epoch 28/50
721/721 [==============================] - 0s 59us/step - loss: 280.5901 - val_loss: 282.9073
Epoch 29/50
721/721 [==============================] - 0s 57us/step - loss: 267.7341 - val_loss: 271.2110
Epoch 30/50
721/721 [==============================] - 0s 57us/step - loss: 255.6019 - val_loss: 260.9341
Epoch 31/50
721/721 [==============================] - 0s 58us/step - loss: 245.5926 - val_loss: 251.9283
Epoch 32/50
721/721 [==============================] - 0s 59us/step - loss: 236.6564 - val_loss: 244.3982
Epoch 33/50
721/721 [==============================] - 0s 60us/step - loss: 229.5421 - val_loss: 239.2802
Epoch 34/50
721/721 [==============================] - 0s 61us/step - loss: 222.3415 - val_loss: 231.7857
Epoch 35/50
721/721 [==============================] - 0s 61us/step - loss: 216.3936 - val_loss: 226.2001
Epoch 36/50
721/721 [==============================] - 0s 

Epoch 3/50
721/721 [==============================] - 0s 57us/step - loss: 4441.5476 - val_loss: 4158.8149
Epoch 4/50
721/721 [==============================] - 0s 55us/step - loss: 3730.9998 - val_loss: 3761.1539
Epoch 5/50
721/721 [==============================] - 0s 56us/step - loss: 3349.5883 - val_loss: 3451.8796
Epoch 6/50
721/721 [==============================] - 0s 56us/step - loss: 3079.2442 - val_loss: 3200.1441
Epoch 7/50
721/721 [==============================] - 0s 61us/step - loss: 2854.8480 - val_loss: 2984.9417
Epoch 8/50
721/721 [==============================] - 0s 63us/step - loss: 2660.5764 - val_loss: 2773.9768
Epoch 9/50
721/721 [==============================] - 0s 62us/step - loss: 2474.3318 - val_loss: 2581.1626
Epoch 10/50
721/721 [==============================] - 0s 61us/step - loss: 2297.9532 - val_loss: 2400.4117
Epoch 11/50
721/721 [==============================] - 0s 61us/step - loss: 2131.2610 - val_loss: 2226.4000
Epoch 12/50
721/721 [==============

721/721 [==============================] - 0s 60us/step - loss: 325.6973 - val_loss: 395.8841
Epoch 30/50
721/721 [==============================] - 0s 58us/step - loss: 314.3394 - val_loss: 382.2220
Epoch 31/50
721/721 [==============================] - 0s 60us/step - loss: 306.5963 - val_loss: 369.5080
Epoch 32/50
721/721 [==============================] - 0s 61us/step - loss: 298.0844 - val_loss: 359.6946
Epoch 33/50
721/721 [==============================] - 0s 64us/step - loss: 289.5683 - val_loss: 353.7023
Epoch 34/50
721/721 [==============================] - 0s 63us/step - loss: 280.7332 - val_loss: 337.7386
Epoch 35/50
721/721 [==============================] - 0s 59us/step - loss: 270.3855 - val_loss: 328.0099
Epoch 36/50
721/721 [==============================] - 0s 58us/step - loss: 263.3188 - val_loss: 322.3279
Epoch 37/50
721/721 [==============================] - 0s 58us/step - loss: 256.4096 - val_loss: 306.4149
Epoch 38/50
721/721 [==============================] - 0s 

721/721 [==============================] - 0s 58us/step - loss: 3050.9006 - val_loss: 2671.2754
Epoch 5/50
721/721 [==============================] - 0s 58us/step - loss: 2428.7100 - val_loss: 2293.7736
Epoch 6/50
721/721 [==============================] - 0s 58us/step - loss: 2121.2326 - val_loss: 2037.2420
Epoch 7/50
721/721 [==============================] - 0s 57us/step - loss: 1908.7012 - val_loss: 1845.1634
Epoch 8/50
721/721 [==============================] - 0s 58us/step - loss: 1732.7977 - val_loss: 1723.2714
Epoch 9/50
721/721 [==============================] - 0s 58us/step - loss: 1587.0305 - val_loss: 1568.4957
Epoch 10/50
721/721 [==============================] - 0s 58us/step - loss: 1457.8918 - val_loss: 1444.5656
Epoch 11/50
721/721 [==============================] - 0s 58us/step - loss: 1333.0384 - val_loss: 1323.5703
Epoch 12/50
721/721 [==============================] - 0s 57us/step - loss: 1219.2690 - val_loss: 1214.9173
Epoch 13/50
721/721 [========================

721/721 [==============================] - 0s 68us/step - loss: 125.3043 - val_loss: 141.3539
Epoch 31/50
721/721 [==============================] - 0s 63us/step - loss: 122.0231 - val_loss: 138.9106
Epoch 32/50
721/721 [==============================] - 0s 60us/step - loss: 119.5268 - val_loss: 136.8894
Epoch 33/50
721/721 [==============================] - 0s 59us/step - loss: 117.8641 - val_loss: 134.6534
Epoch 34/50
721/721 [==============================] - 0s 59us/step - loss: 115.2638 - val_loss: 134.0160
Epoch 35/50
721/721 [==============================] - 0s 60us/step - loss: 113.2706 - val_loss: 131.8572
Epoch 36/50
721/721 [==============================] - 0s 62us/step - loss: 111.6700 - val_loss: 131.5428
Epoch 37/50
721/721 [==============================] - 0s 64us/step - loss: 110.7253 - val_loss: 129.9632
Epoch 38/50
721/721 [==============================] - 0s 63us/step - loss: 109.8077 - val_loss: 129.6657
Epoch 39/50
721/721 [==============================] - 0s 

721/721 [==============================] - 0s 67us/step - loss: 767.9345 - val_loss: 668.4961
Epoch 7/50
721/721 [==============================] - 0s 71us/step - loss: 637.5553 - val_loss: 579.7020
Epoch 8/50
721/721 [==============================] - 0s 67us/step - loss: 556.1329 - val_loss: 516.2786
Epoch 9/50
721/721 [==============================] - 0s 66us/step - loss: 487.5156 - val_loss: 467.3320
Epoch 10/50
721/721 [==============================] - 0s 67us/step - loss: 436.9346 - val_loss: 428.6529
Epoch 11/50
721/721 [==============================] - 0s 68us/step - loss: 398.8950 - val_loss: 398.1928
Epoch 12/50
721/721 [==============================] - 0s 66us/step - loss: 371.2590 - val_loss: 376.0810
Epoch 13/50
721/721 [==============================] - 0s 67us/step - loss: 346.3555 - val_loss: 356.7986
Epoch 14/50
721/721 [==============================] - 0s 66us/step - loss: 324.9036 - val_loss: 340.2707
Epoch 15/50
721/721 [==============================] - 0s 61u

Epoch 33/50
721/721 [==============================] - 0s 59us/step - loss: 103.6477 - val_loss: 110.7660
Epoch 34/50
721/721 [==============================] - 0s 58us/step - loss: 102.1234 - val_loss: 108.9458
Epoch 35/50
721/721 [==============================] - 0s 58us/step - loss: 100.2037 - val_loss: 107.1504
Epoch 36/50
721/721 [==============================] - 0s 58us/step - loss: 96.9543 - val_loss: 134.6302
Epoch 37/50
721/721 [==============================] - 0s 58us/step - loss: 112.8108 - val_loss: 108.7556
Epoch 38/50
721/721 [==============================] - 0s 57us/step - loss: 99.4937 - val_loss: 111.9079
Epoch 39/50
721/721 [==============================] - 0s 58us/step - loss: 95.6069 - val_loss: 103.9607
Epoch 40/50
721/721 [==============================] - 0s 57us/step - loss: 97.8711 - val_loss: 117.3686
Epoch 41/50
721/721 [==============================] - 0s 57us/step - loss: 99.5391 - val_loss: 103.8310
Epoch 42/50
721/721 [==============================

721/721 [==============================] - 0s 56us/step - loss: 495.5487 - val_loss: 461.8946
Epoch 10/50
721/721 [==============================] - 0s 59us/step - loss: 412.8660 - val_loss: 399.2977
Epoch 11/50
721/721 [==============================] - 0s 61us/step - loss: 358.5050 - val_loss: 348.7286
Epoch 12/50
721/721 [==============================] - 0s 58us/step - loss: 318.0653 - val_loss: 313.6100
Epoch 13/50
721/721 [==============================] - 0s 56us/step - loss: 264.6614 - val_loss: 275.4524
Epoch 14/50
721/721 [==============================] - 0s 57us/step - loss: 231.2315 - val_loss: 246.7300
Epoch 15/50
721/721 [==============================] - 0s 58us/step - loss: 206.8609 - val_loss: 221.6700
Epoch 16/50
721/721 [==============================] - 0s 57us/step - loss: 186.4691 - val_loss: 200.1475
Epoch 17/50
721/721 [==============================] - 0s 57us/step - loss: 169.5434 - val_loss: 185.4509
Epoch 18/50
721/721 [==============================] - 0s 

Epoch 36/50
721/721 [==============================] - 0s 58us/step - loss: 306.4002 - val_loss: 336.3335
Epoch 37/50
721/721 [==============================] - 0s 56us/step - loss: 303.6251 - val_loss: 332.7405
Epoch 38/50
721/721 [==============================] - 0s 55us/step - loss: 298.8360 - val_loss: 327.7022
Epoch 39/50
721/721 [==============================] - 0s 56us/step - loss: 295.0092 - val_loss: 324.8648
Epoch 40/50
721/721 [==============================] - 0s 56us/step - loss: 291.1305 - val_loss: 320.1065
Epoch 41/50
721/721 [==============================] - 0s 56us/step - loss: 287.7437 - val_loss: 316.0796
Epoch 42/50
721/721 [==============================] - 0s 57us/step - loss: 284.3559 - val_loss: 313.5071
Epoch 43/50
721/721 [==============================] - 0s 56us/step - loss: 281.0772 - val_loss: 309.0473
Epoch 44/50
721/721 [==============================] - 0s 56us/step - loss: 278.5507 - val_loss: 305.5188
Epoch 45/50
721/721 [=========================

Epoch 12/50
721/721 [==============================] - 0s 58us/step - loss: 5100.5512 - val_loss: 5449.0618
Epoch 13/50
721/721 [==============================] - 0s 58us/step - loss: 4944.7836 - val_loss: 5312.7891
Epoch 14/50
721/721 [==============================] - 0s 57us/step - loss: 4789.2618 - val_loss: 5159.8782
Epoch 15/50
721/721 [==============================] - 0s 58us/step - loss: 4642.9979 - val_loss: 5016.9579
Epoch 16/50
721/721 [==============================] - 0s 59us/step - loss: 4500.7031 - val_loss: 4872.0755
Epoch 17/50
721/721 [==============================] - 0s 57us/step - loss: 4356.9648 - val_loss: 4746.7475
Epoch 18/50
721/721 [==============================] - 0s 58us/step - loss: 4225.4367 - val_loss: 4605.9060
Epoch 19/50
721/721 [==============================] - 0s 57us/step - loss: 4092.9221 - val_loss: 4480.3378
Epoch 20/50
721/721 [==============================] - 0s 57us/step - loss: 3969.5385 - val_loss: 4350.4939
Epoch 21/50
721/721 [=======

721/721 [==============================] - 0s 56us/step - loss: 1558.1029 - val_loss: 1752.2221
Epoch 38/50
721/721 [==============================] - 0s 57us/step - loss: 1534.5268 - val_loss: 1731.9080
Epoch 39/50
721/721 [==============================] - 0s 57us/step - loss: 1519.3812 - val_loss: 1701.4321
Epoch 40/50
721/721 [==============================] - 0s 57us/step - loss: 1495.3686 - val_loss: 1687.0725
Epoch 41/50
721/721 [==============================] - 0s 57us/step - loss: 1474.4939 - val_loss: 1658.8259
Epoch 42/50
721/721 [==============================] - 0s 61us/step - loss: 1454.5685 - val_loss: 1636.9653
Epoch 43/50
721/721 [==============================] - 0s 59us/step - loss: 1436.9828 - val_loss: 1614.6860
Epoch 44/50
721/721 [==============================] - 0s 57us/step - loss: 1418.7949 - val_loss: 1591.5672
Epoch 45/50
721/721 [==============================] - 0s 59us/step - loss: 1400.5346 - val_loss: 1573.9136
Epoch 46/50
721/721 [===================

721/721 [==============================] - 0s 57us/step - loss: 1449.1725 - val_loss: 1364.7108
Epoch 13/50
721/721 [==============================] - 0s 57us/step - loss: 1401.9173 - val_loss: 1320.2182
Epoch 14/50
721/721 [==============================] - 0s 58us/step - loss: 1350.9109 - val_loss: 1276.3368
Epoch 15/50
721/721 [==============================] - 0s 58us/step - loss: 1303.6436 - val_loss: 1232.8196
Epoch 16/50
721/721 [==============================] - 0s 57us/step - loss: 1257.8283 - val_loss: 1191.0658
Epoch 17/50
721/721 [==============================] - 0s 59us/step - loss: 1208.9198 - val_loss: 1151.9738
Epoch 18/50
721/721 [==============================] - 0s 57us/step - loss: 1165.6421 - val_loss: 1112.0726
Epoch 19/50
721/721 [==============================] - 0s 58us/step - loss: 1121.7915 - val_loss: 1074.6058
Epoch 20/50
721/721 [==============================] - 0s 57us/step - loss: 1081.2162 - val_loss: 1036.7553
Epoch 21/50
721/721 [===================

Epoch 38/50
721/721 [==============================] - 0s 65us/step - loss: 1245.7084 - val_loss: 1463.1599
Epoch 39/50
721/721 [==============================] - 0s 65us/step - loss: 1182.7514 - val_loss: 1392.5370
Epoch 40/50
721/721 [==============================] - 0s 65us/step - loss: 1125.3989 - val_loss: 1328.7957
Epoch 41/50
721/721 [==============================] - 0s 63us/step - loss: 1071.3763 - val_loss: 1270.9919
Epoch 42/50
721/721 [==============================] - 0s 62us/step - loss: 1027.1886 - val_loss: 1217.4941
Epoch 43/50
721/721 [==============================] - 0s 59us/step - loss: 988.9554 - val_loss: 1166.7123
Epoch 44/50
721/721 [==============================] - 0s 58us/step - loss: 951.4557 - val_loss: 1125.7467
Epoch 45/50
721/721 [==============================] - 0s 60us/step - loss: 916.4661 - val_loss: 1087.7906
Epoch 46/50
721/721 [==============================] - 0s 60us/step - loss: 886.7228 - val_loss: 1052.8085
Epoch 47/50
721/721 [===========

721/721 [==============================] - 0s 58us/step - loss: 148.8377 - val_loss: 162.5989
Epoch 15/50
721/721 [==============================] - 0s 64us/step - loss: 142.2714 - val_loss: 156.6724
Epoch 16/50
721/721 [==============================] - 0s 61us/step - loss: 137.4793 - val_loss: 165.4077
Epoch 17/50
721/721 [==============================] - 0s 60us/step - loss: 135.9978 - val_loss: 149.9637
Epoch 18/50
721/721 [==============================] - 0s 56us/step - loss: 131.5407 - val_loss: 147.7616
Epoch 19/50
721/721 [==============================] - 0s 58us/step - loss: 137.3222 - val_loss: 149.6132
Epoch 20/50
721/721 [==============================] - 0s 60us/step - loss: 134.4472 - val_loss: 143.4696
Epoch 21/50
721/721 [==============================] - 0s 61us/step - loss: 126.1432 - val_loss: 143.5136
Epoch 22/50
721/721 [==============================] - 0s 58us/step - loss: 126.0917 - val_loss: 158.2103
Epoch 23/50
721/721 [==============================] - 0s 

Epoch 41/50
721/721 [==============================] - 0s 61us/step - loss: 108.7691 - val_loss: 130.7891
Epoch 42/50
721/721 [==============================] - 0s 58us/step - loss: 107.8845 - val_loss: 129.6966
Epoch 43/50
721/721 [==============================] - 0s 58us/step - loss: 106.8661 - val_loss: 128.6461
Epoch 44/50
721/721 [==============================] - 0s 59us/step - loss: 105.6818 - val_loss: 131.6481
Epoch 45/50
721/721 [==============================] - 0s 67us/step - loss: 105.1357 - val_loss: 127.2186
Epoch 46/50
721/721 [==============================] - 0s 59us/step - loss: 105.2451 - val_loss: 127.9658
Epoch 47/50
721/721 [==============================] - 0s 60us/step - loss: 104.3294 - val_loss: 123.8880
Epoch 48/50
721/721 [==============================] - 0s 59us/step - loss: 102.9717 - val_loss: 123.9974
Epoch 49/50
721/721 [==============================] - 0s 59us/step - loss: 102.1412 - val_loss: 122.8270
Epoch 50/50
721/721 [=========================

721/721 [==============================] - 0s 59us/step - loss: 2479.1274 - val_loss: 1730.0400
Epoch 17/50
721/721 [==============================] - 0s 62us/step - loss: 1365.4241 - val_loss: 1113.8999
Epoch 18/50
721/721 [==============================] - 0s 64us/step - loss: 937.6995 - val_loss: 908.9568
Epoch 19/50
721/721 [==============================] - 0s 63us/step - loss: 797.6607 - val_loss: 843.1182
Epoch 20/50
721/721 [==============================] - 0s 63us/step - loss: 748.1654 - val_loss: 820.8658
Epoch 21/50
721/721 [==============================] - 0s 60us/step - loss: 727.2522 - val_loss: 804.6947
Epoch 22/50
721/721 [==============================] - 0s 63us/step - loss: 713.2424 - val_loss: 795.1394
Epoch 23/50
721/721 [==============================] - 0s 63us/step - loss: 700.5809 - val_loss: 779.3408
Epoch 24/50
721/721 [==============================] - 0s 62us/step - loss: 687.2925 - val_loss: 766.7303
Epoch 25/50
721/721 [==============================] -

Epoch 42/50
721/721 [==============================] - 0s 57us/step - loss: 3455.4945 - val_loss: 3651.2412
Epoch 43/50
721/721 [==============================] - 0s 59us/step - loss: 3384.0381 - val_loss: 3575.3656
Epoch 44/50
721/721 [==============================] - 0s 56us/step - loss: 3310.7876 - val_loss: 3486.5184
Epoch 45/50
721/721 [==============================] - 0s 58us/step - loss: 3241.2054 - val_loss: 3416.9554
Epoch 46/50
721/721 [==============================] - 0s 57us/step - loss: 3171.5807 - val_loss: 3339.7472
Epoch 47/50
721/721 [==============================] - 0s 58us/step - loss: 3109.1642 - val_loss: 3273.9791
Epoch 48/50
721/721 [==============================] - 0s 57us/step - loss: 3036.9742 - val_loss: 3204.6566
Epoch 49/50
721/721 [==============================] - 0s 57us/step - loss: 2976.8868 - val_loss: 3145.8504
Epoch 50/50
721/721 [==============================] - 0s 57us/step - loss: 2914.8633 - val_loss: 3074.0638
Sample 26
Train on 721 sampl

721/721 [==============================] - 0s 59us/step - loss: 2444.8059 - val_loss: 2632.3794
Epoch 18/50
721/721 [==============================] - 0s 58us/step - loss: 2359.0261 - val_loss: 2549.1729
Epoch 19/50
721/721 [==============================] - 0s 62us/step - loss: 2279.5296 - val_loss: 2462.9474
Epoch 20/50
721/721 [==============================] - 0s 58us/step - loss: 2199.4801 - val_loss: 2382.4025
Epoch 21/50
721/721 [==============================] - 0s 59us/step - loss: 2129.7285 - val_loss: 2304.8384
Epoch 22/50
721/721 [==============================] - 0s 58us/step - loss: 2058.5157 - val_loss: 2229.6624
Epoch 23/50
721/721 [==============================] - 0s 58us/step - loss: 1988.8470 - val_loss: 2156.7223
Epoch 24/50
721/721 [==============================] - 0s 59us/step - loss: 1921.2074 - val_loss: 2093.0315
Epoch 25/50
721/721 [==============================] - 0s 60us/step - loss: 1859.8297 - val_loss: 2024.8029
Epoch 26/50
721/721 [===================

721/721 [==============================] - 0s 58us/step - loss: 2750.8421 - val_loss: 2590.4421
Epoch 43/50
721/721 [==============================] - 0s 64us/step - loss: 2650.1661 - val_loss: 2501.7866
Epoch 44/50
721/721 [==============================] - 0s 63us/step - loss: 2553.0837 - val_loss: 2412.3818
Epoch 45/50
721/721 [==============================] - 0s 62us/step - loss: 2459.5828 - val_loss: 2339.3627
Epoch 46/50
721/721 [==============================] - 0s 61us/step - loss: 2373.0225 - val_loss: 2256.9386
Epoch 47/50
721/721 [==============================] - 0s 60us/step - loss: 2286.4003 - val_loss: 2181.0551
Epoch 48/50
721/721 [==============================] - 0s 57us/step - loss: 2207.3930 - val_loss: 2110.6279
Epoch 49/50
721/721 [==============================] - 0s 57us/step - loss: 2130.7409 - val_loss: 2035.1997
Epoch 50/50
721/721 [==============================] - 0s 57us/step - loss: 2055.0460 - val_loss: 1975.9741
Sample 29
Train on 721 samples, validate

721/721 [==============================] - 0s 67us/step - loss: 451.6248 - val_loss: 480.9371
Epoch 19/50
721/721 [==============================] - 0s 67us/step - loss: 429.2507 - val_loss: 459.2439
Epoch 20/50
721/721 [==============================] - 0s 68us/step - loss: 408.0392 - val_loss: 439.4950
Epoch 21/50
721/721 [==============================] - 0s 69us/step - loss: 389.5349 - val_loss: 419.1532
Epoch 22/50
721/721 [==============================] - 0s 62us/step - loss: 372.0339 - val_loss: 400.0771
Epoch 23/50
721/721 [==============================] - 0s 62us/step - loss: 354.5028 - val_loss: 383.3780
Epoch 24/50
721/721 [==============================] - 0s 61us/step - loss: 337.6861 - val_loss: 363.5713
Epoch 25/50
721/721 [==============================] - 0s 64us/step - loss: 321.9649 - val_loss: 349.6600
Epoch 26/50
721/721 [==============================] - 0s 61us/step - loss: 309.2830 - val_loss: 332.1556
Epoch 27/50
721/721 [==============================] - 0s 

Epoch 45/50
721/721 [==============================] - 0s 70us/step - loss: 114.8033 - val_loss: 140.0804
Epoch 46/50
721/721 [==============================] - 0s 66us/step - loss: 113.1267 - val_loss: 140.0580
Epoch 47/50
721/721 [==============================] - 0s 61us/step - loss: 114.0767 - val_loss: 139.0634
Epoch 48/50
721/721 [==============================] - 0s 59us/step - loss: 115.1564 - val_loss: 138.4919
Epoch 49/50
721/721 [==============================] - 0s 58us/step - loss: 115.6626 - val_loss: 138.1889
Epoch 50/50
721/721 [==============================] - 0s 58us/step - loss: 112.9192 - val_loss: 137.9097
Sample 32
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 686us/step - loss: 153821.9659 - val_loss: 113520.3975
Epoch 2/50
721/721 [==============================] - 0s 60us/step - loss: 88479.0154 - val_loss: 62884.4730
Epoch 3/50
721/721 [==============================] - 0s 61us/step - loss: 46087.5365 -

721/721 [==============================] - 0s 58us/step - loss: 1984.0753 - val_loss: 2096.3471
Epoch 21/50
721/721 [==============================] - 0s 58us/step - loss: 1891.0695 - val_loss: 1996.1993
Epoch 22/50
721/721 [==============================] - 0s 57us/step - loss: 1799.8350 - val_loss: 1901.4343
Epoch 23/50
721/721 [==============================] - 0s 59us/step - loss: 1713.2504 - val_loss: 1814.7113
Epoch 24/50
721/721 [==============================] - 0s 61us/step - loss: 1630.9521 - val_loss: 1722.8432
Epoch 25/50
721/721 [==============================] - 0s 57us/step - loss: 1549.4113 - val_loss: 1638.3816
Epoch 26/50
721/721 [==============================] - 0s 56us/step - loss: 1470.9837 - val_loss: 1558.8503
Epoch 27/50
721/721 [==============================] - 0s 57us/step - loss: 1397.9942 - val_loss: 1484.9715
Epoch 28/50
721/721 [==============================] - 0s 58us/step - loss: 1327.7380 - val_loss: 1410.2669
Epoch 29/50
721/721 [===================

721/721 [==============================] - 0s 58us/step - loss: 177.2608 - val_loss: 187.8291
Epoch 47/50
721/721 [==============================] - 0s 61us/step - loss: 171.9403 - val_loss: 182.8294
Epoch 48/50
721/721 [==============================] - 0s 57us/step - loss: 167.3866 - val_loss: 178.9125
Epoch 49/50
721/721 [==============================] - 0s 58us/step - loss: 163.4169 - val_loss: 173.9634
Epoch 50/50
721/721 [==============================] - 0s 58us/step - loss: 159.7963 - val_loss: 169.7874
Sample 35
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 612us/step - loss: 611363.0605 - val_loss: 473703.3780
Epoch 2/50
721/721 [==============================] - 0s 57us/step - loss: 370022.2052 - val_loss: 280954.8186
Epoch 3/50
721/721 [==============================] - 0s 60us/step - loss: 216502.8067 - val_loss: 162623.5457
Epoch 4/50
721/721 [==============================] - 0s 56us/step - loss: 123655.3415 - val

721/721 [==============================] - 0s 58us/step - loss: 3461.9728 - val_loss: 3197.9640
Epoch 21/50
721/721 [==============================] - 0s 57us/step - loss: 3384.6658 - val_loss: 3126.6040
Epoch 22/50
721/721 [==============================] - 0s 59us/step - loss: 3308.5012 - val_loss: 3054.7423
Epoch 23/50
721/721 [==============================] - 0s 58us/step - loss: 3231.8617 - val_loss: 2984.5836
Epoch 24/50
721/721 [==============================] - 0s 59us/step - loss: 3158.7920 - val_loss: 2914.4311
Epoch 25/50
721/721 [==============================] - 0s 59us/step - loss: 3081.9381 - val_loss: 2846.0428
Epoch 26/50
721/721 [==============================] - 0s 58us/step - loss: 3009.3254 - val_loss: 2778.5697
Epoch 27/50
721/721 [==============================] - 0s 58us/step - loss: 2935.9432 - val_loss: 2709.7814
Epoch 28/50
721/721 [==============================] - 0s 57us/step - loss: 2860.8491 - val_loss: 2644.5859
Epoch 29/50
721/721 [===================

721/721 [==============================] - 0s 62us/step - loss: 97.3345 - val_loss: 99.3399
Epoch 47/50
721/721 [==============================] - 0s 61us/step - loss: 94.3090 - val_loss: 99.7013
Epoch 48/50
721/721 [==============================] - 0s 60us/step - loss: 97.2947 - val_loss: 103.3525
Epoch 49/50
721/721 [==============================] - 0s 62us/step - loss: 93.9667 - val_loss: 96.7934
Epoch 50/50
721/721 [==============================] - 0s 60us/step - loss: 93.0900 - val_loss: 103.2787
Sample 38
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 654us/step - loss: 3602.3462 - val_loss: 2033.6417
Epoch 2/50
721/721 [==============================] - 0s 57us/step - loss: 1817.3286 - val_loss: 1590.4895
Epoch 3/50
721/721 [==============================] - 0s 57us/step - loss: 1408.2301 - val_loss: 1188.9068
Epoch 4/50
721/721 [==============================] - 0s 57us/step - loss: 1055.3482 - val_loss: 876.6621
Epoch 

Epoch 22/50
721/721 [==============================] - 0s 59us/step - loss: 2024.7249 - val_loss: 2146.0030
Epoch 23/50
721/721 [==============================] - 0s 57us/step - loss: 1974.6293 - val_loss: 2090.0158
Epoch 24/50
721/721 [==============================] - 0s 59us/step - loss: 1920.6566 - val_loss: 2032.6849
Epoch 25/50
721/721 [==============================] - 0s 58us/step - loss: 1870.5135 - val_loss: 1976.2944
Epoch 26/50
721/721 [==============================] - 0s 59us/step - loss: 1818.9042 - val_loss: 1921.8096
Epoch 27/50
721/721 [==============================] - 0s 58us/step - loss: 1770.1205 - val_loss: 1866.9529
Epoch 28/50
721/721 [==============================] - 0s 57us/step - loss: 1724.5555 - val_loss: 1817.1318
Epoch 29/50
721/721 [==============================] - 0s 58us/step - loss: 1671.6111 - val_loss: 1761.3698
Epoch 30/50
721/721 [==============================] - 0s 59us/step - loss: 1624.7278 - val_loss: 1708.7256
Epoch 31/50
721/721 [=======

721/721 [==============================] - 0s 56us/step - loss: 112.4592 - val_loss: 132.1226
Epoch 49/50
721/721 [==============================] - 0s 58us/step - loss: 112.1846 - val_loss: 132.9890
Epoch 50/50
721/721 [==============================] - 0s 57us/step - loss: 110.7943 - val_loss: 129.7189
Sample 41
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 652us/step - loss: 152993.9703 - val_loss: 96494.4529
Epoch 2/50
721/721 [==============================] - 0s 58us/step - loss: 70509.9709 - val_loss: 42064.6910
Epoch 3/50
721/721 [==============================] - 0s 59us/step - loss: 30015.4314 - val_loss: 16246.6511
Epoch 4/50
721/721 [==============================] - 0s 63us/step - loss: 10988.8342 - val_loss: 4734.4881
Epoch 5/50
721/721 [==============================] - 0s 62us/step - loss: 2933.9672 - val_loss: 1589.4038
Epoch 6/50
721/721 [==============================] - 0s 62us/step - loss: 1499.0727 - val_los

Epoch 24/50
721/721 [==============================] - 0s 66us/step - loss: 1392.3424 - val_loss: 1499.1303
Epoch 25/50
721/721 [==============================] - 0s 64us/step - loss: 1306.6410 - val_loss: 1426.5179
Epoch 26/50
721/721 [==============================] - 0s 64us/step - loss: 1233.4270 - val_loss: 1346.6147
Epoch 27/50
721/721 [==============================] - 0s 63us/step - loss: 1165.0122 - val_loss: 1256.8445
Epoch 28/50
721/721 [==============================] - 0s 63us/step - loss: 1097.2709 - val_loss: 1200.4001
Epoch 29/50
721/721 [==============================] - 0s 63us/step - loss: 1034.9717 - val_loss: 1139.8512
Epoch 30/50
721/721 [==============================] - 0s 63us/step - loss: 978.2278 - val_loss: 1072.9193
Epoch 31/50
721/721 [==============================] - 0s 62us/step - loss: 928.8283 - val_loss: 1020.9926
Epoch 32/50
721/721 [==============================] - 0s 62us/step - loss: 879.5277 - val_loss: 964.0644
Epoch 33/50
721/721 [===========

721/721 [==============================] - 0s 59us/step - loss: 207.8066 - val_loss: 227.0994
Sample 44
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 684us/step - loss: 48623.2682 - val_loss: 29067.5785
Epoch 2/50
721/721 [==============================] - 0s 60us/step - loss: 18372.4952 - val_loss: 9500.8893
Epoch 3/50
721/721 [==============================] - 0s 59us/step - loss: 5500.5492 - val_loss: 2830.0054
Epoch 4/50
721/721 [==============================] - 0s 60us/step - loss: 1736.4376 - val_loss: 1370.5773
Epoch 5/50
721/721 [==============================] - 0s 59us/step - loss: 1054.5568 - val_loss: 1197.5821
Epoch 6/50
721/721 [==============================] - 0s 61us/step - loss: 971.4443 - val_loss: 1153.4084
Epoch 7/50
721/721 [==============================] - 0s 60us/step - loss: 939.8732 - val_loss: 1113.1175
Epoch 8/50
721/721 [==============================] - 0s 65us/step - loss: 902.6219 - val_loss: 106

721/721 [==============================] - 0s 64us/step - loss: 266.3315 - val_loss: 295.7578
Epoch 27/50
721/721 [==============================] - 0s 65us/step - loss: 254.3337 - val_loss: 286.2461
Epoch 28/50
721/721 [==============================] - 0s 63us/step - loss: 243.0785 - val_loss: 270.0378
Epoch 29/50
721/721 [==============================] - 0s 63us/step - loss: 233.3048 - val_loss: 261.1012
Epoch 30/50
721/721 [==============================] - 0s 64us/step - loss: 224.9741 - val_loss: 254.1062
Epoch 31/50
721/721 [==============================] - 0s 62us/step - loss: 217.3526 - val_loss: 245.3880
Epoch 32/50
721/721 [==============================] - 0s 61us/step - loss: 210.2272 - val_loss: 237.4121
Epoch 33/50
721/721 [==============================] - 0s 64us/step - loss: 203.6312 - val_loss: 229.3716
Epoch 34/50
721/721 [==============================] - 0s 60us/step - loss: 198.4393 - val_loss: 232.6477
Epoch 35/50
721/721 [==============================] - 0s 

721/721 [==============================] - 0s 680us/step - loss: 221629.6682 - val_loss: 151582.0826
Epoch 2/50
721/721 [==============================] - 0s 62us/step - loss: 98862.7760 - val_loss: 60478.0181
Epoch 3/50
721/721 [==============================] - 0s 67us/step - loss: 33639.0486 - val_loss: 15034.2897
Epoch 4/50
721/721 [==============================] - 0s 60us/step - loss: 6419.0365 - val_loss: 2584.3501
Epoch 5/50
721/721 [==============================] - 0s 58us/step - loss: 1967.0194 - val_loss: 1846.6020
Epoch 6/50
721/721 [==============================] - 0s 57us/step - loss: 1781.8416 - val_loss: 1659.5804
Epoch 7/50
721/721 [==============================] - 0s 60us/step - loss: 1580.1386 - val_loss: 1529.5304
Epoch 8/50
721/721 [==============================] - 0s 59us/step - loss: 1439.3018 - val_loss: 1410.0500
Epoch 9/50
721/721 [==============================] - 0s 58us/step - loss: 1332.1074 - val_loss: 1317.2232
Epoch 10/50
721/721 [==================

721/721 [==============================] - 0s 56us/step - loss: 622.5744 - val_loss: 708.1851
Epoch 28/50
721/721 [==============================] - 0s 56us/step - loss: 592.3308 - val_loss: 677.4284
Epoch 29/50
721/721 [==============================] - 0s 56us/step - loss: 566.7400 - val_loss: 650.7773
Epoch 30/50
721/721 [==============================] - 0s 56us/step - loss: 542.9163 - val_loss: 613.1694
Epoch 31/50
721/721 [==============================] - 0s 56us/step - loss: 515.1935 - val_loss: 589.3469
Epoch 32/50
721/721 [==============================] - 0s 56us/step - loss: 491.4293 - val_loss: 558.8708
Epoch 33/50
721/721 [==============================] - 0s 56us/step - loss: 471.6293 - val_loss: 535.9132
Epoch 34/50
721/721 [==============================] - 0s 56us/step - loss: 450.8925 - val_loss: 514.5219
Epoch 35/50
721/721 [==============================] - 0s 56us/step - loss: 431.6590 - val_loss: 489.9808
Epoch 36/50
721/721 [==============================] - 0s 

In [41]:
#Calculate mean and standard deviation of RMSE list

mean = sum(eval_list) / len(eval_list) 
variance = sum([((x - mean) ** 2) for x in eval_list]) / len(eval_list) 
st_dev = variance ** 0.5


print("The Mean of the RMSE list is : " +str(mean)+ " and the Standard deviation is : " + str(st_dev)) 


The Mean of the RMSE list is : 535.7252699255097 and the Standard deviation is : 809.7241251802326


### Experimenting with Normalized Data

B) Normalize data and compare RMSE with previous outputs

In [42]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

Cement  Blast Furnace Slag   Fly Ash     Water  Superplasticizer  \
0  2.476712           -0.856472 -0.846733 -0.916319         -0.620147   
1  2.476712           -0.856472 -0.846733 -0.916319         -0.620147   
2  0.491187            0.795140 -0.846733  2.174405         -1.038638   
3  0.491187            0.795140 -0.846733  2.174405         -1.038638   
4 -0.790075            0.678079 -0.846733  0.488555         -1.038638   

   Coarse Aggregate  Fine Aggregate       Age  
0          0.862735       -1.217079 -0.279597  
1          1.055651       -1.217079 -0.279597  
2         -0.526262       -2.239829  3.551340  
3         -0.526262       -2.239829  5.055221  
4          0.070492        0.647569  4.976069

In [43]:
#Predict and evaluate

#Starting list that will contain RMSE scores for each sample
eval_list = []

for i in range(samples):
    print("Sample " + str(i))
    #Split data into test and train over each iteration
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=.3, random_state=99)

    #Re-build NN
    model = regression_model()
    
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=EPochs, verbose=1)
    eval_list.append(model.evaluate(X_test, y_test, verbose=0))

    

Sample 0
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 658us/step - loss: 1598.4407 - val_loss: 1471.8651
Epoch 2/50
721/721 [==============================] - 0s 66us/step - loss: 1586.5775 - val_loss: 1460.5762
Epoch 3/50
721/721 [==============================] - 0s 65us/step - loss: 1574.9613 - val_loss: 1449.0014
Epoch 4/50
721/721 [==============================] - 0s 65us/step - loss: 1562.6953 - val_loss: 1437.2040
Epoch 5/50
721/721 [==============================] - 0s 64us/step - loss: 1549.8883 - val_loss: 1424.4418
Epoch 6/50
721/721 [==============================] - 0s 62us/step - loss: 1535.8062 - val_loss: 1410.6635
Epoch 7/50
721/721 [==============================] - 0s 64us/step - loss: 1520.8216 - val_loss: 1395.4601
Epoch 8/50
721/721 [==============================] - 0s 62us/step - loss: 1503.9003 - val_loss: 1379.2487
Epoch 9/50
721/721 [==============================] - 0s 63us/step - loss: 1485.6104 - v

721/721 [==============================] - 0s 63us/step - loss: 1048.9336 - val_loss: 943.5747
Epoch 27/50
721/721 [==============================] - 0s 62us/step - loss: 1017.6012 - val_loss: 915.3506
Epoch 28/50
721/721 [==============================] - 0s 60us/step - loss: 985.6995 - val_loss: 887.3083
Epoch 29/50
721/721 [==============================] - 0s 63us/step - loss: 953.8171 - val_loss: 858.7709
Epoch 30/50
721/721 [==============================] - 0s 63us/step - loss: 921.6996 - val_loss: 829.7043
Epoch 31/50
721/721 [==============================] - 0s 63us/step - loss: 888.7935 - val_loss: 801.1331
Epoch 32/50
721/721 [==============================] - 0s 63us/step - loss: 855.9774 - val_loss: 772.2466
Epoch 33/50
721/721 [==============================] - 0s 61us/step - loss: 823.4230 - val_loss: 743.1816
Epoch 34/50
721/721 [==============================] - 0s 60us/step - loss: 790.4047 - val_loss: 715.3682
Epoch 35/50
721/721 [==============================] - 0

Epoch 2/50
721/721 [==============================] - 0s 62us/step - loss: 1591.6244 - val_loss: 1463.5586
Epoch 3/50
721/721 [==============================] - 0s 61us/step - loss: 1572.9257 - val_loss: 1446.4303
Epoch 4/50
721/721 [==============================] - 0s 59us/step - loss: 1554.1054 - val_loss: 1429.3912
Epoch 5/50
721/721 [==============================] - 0s 60us/step - loss: 1535.5811 - val_loss: 1411.8469
Epoch 6/50
721/721 [==============================] - 0s 58us/step - loss: 1516.3938 - val_loss: 1394.2153
Epoch 7/50
721/721 [==============================] - 0s 60us/step - loss: 1497.1247 - val_loss: 1376.0099
Epoch 8/50
721/721 [==============================] - 0s 59us/step - loss: 1477.3108 - val_loss: 1357.7244
Epoch 9/50
721/721 [==============================] - 0s 59us/step - loss: 1457.1064 - val_loss: 1339.1026
Epoch 10/50
721/721 [==============================] - 0s 63us/step - loss: 1436.7797 - val_loss: 1319.5172
Epoch 11/50
721/721 [===============

Epoch 28/50
721/721 [==============================] - 0s 60us/step - loss: 1216.7721 - val_loss: 1121.0881
Epoch 29/50
721/721 [==============================] - 0s 61us/step - loss: 1189.5565 - val_loss: 1095.5980
Epoch 30/50
721/721 [==============================] - 0s 59us/step - loss: 1161.4954 - val_loss: 1070.1074
Epoch 31/50
721/721 [==============================] - 0s 60us/step - loss: 1133.3137 - val_loss: 1044.2543
Epoch 32/50
721/721 [==============================] - 0s 61us/step - loss: 1104.7647 - val_loss: 1018.1296
Epoch 33/50
721/721 [==============================] - 0s 60us/step - loss: 1075.8025 - val_loss: 991.9142
Epoch 34/50
721/721 [==============================] - 0s 64us/step - loss: 1046.5055 - val_loss: 965.8559
Epoch 35/50
721/721 [==============================] - 0s 63us/step - loss: 1017.2710 - val_loss: 938.9212
Epoch 36/50
721/721 [==============================] - 0s 65us/step - loss: 987.4891 - val_loss: 911.9495
Epoch 37/50
721/721 [============

Epoch 4/50
721/721 [==============================] - 0s 60us/step - loss: 1562.6554 - val_loss: 1433.9548
Epoch 5/50
721/721 [==============================] - 0s 63us/step - loss: 1543.4544 - val_loss: 1416.3714
Epoch 6/50
721/721 [==============================] - 0s 64us/step - loss: 1523.6867 - val_loss: 1398.0092
Epoch 7/50
721/721 [==============================] - 0s 57us/step - loss: 1503.0338 - val_loss: 1378.6147
Epoch 8/50
721/721 [==============================] - 0s 57us/step - loss: 1481.0587 - val_loss: 1358.9204
Epoch 9/50
721/721 [==============================] - 0s 64us/step - loss: 1458.5673 - val_loss: 1337.6818
Epoch 10/50
721/721 [==============================] - 0s 60us/step - loss: 1434.8510 - val_loss: 1315.9277
Epoch 11/50
721/721 [==============================] - 0s 64us/step - loss: 1410.2191 - val_loss: 1293.2812
Epoch 12/50
721/721 [==============================] - 0s 61us/step - loss: 1384.4460 - val_loss: 1270.0447
Epoch 13/50
721/721 [=============

721/721 [==============================] - 0s 58us/step - loss: 764.9992 - val_loss: 715.6949
Epoch 31/50
721/721 [==============================] - 0s 61us/step - loss: 732.4880 - val_loss: 686.7635
Epoch 32/50
721/721 [==============================] - 0s 60us/step - loss: 700.7017 - val_loss: 658.9453
Epoch 33/50
721/721 [==============================] - 0s 59us/step - loss: 669.7973 - val_loss: 631.9324
Epoch 34/50
721/721 [==============================] - 0s 57us/step - loss: 640.2710 - val_loss: 605.8161
Epoch 35/50
721/721 [==============================] - 0s 62us/step - loss: 611.2288 - val_loss: 581.0330
Epoch 36/50
721/721 [==============================] - 0s 58us/step - loss: 583.7038 - val_loss: 556.8243
Epoch 37/50
721/721 [==============================] - 0s 59us/step - loss: 557.0396 - val_loss: 533.6862
Epoch 38/50
721/721 [==============================] - 0s 60us/step - loss: 531.8734 - val_loss: 511.3180
Epoch 39/50
721/721 [==============================] - 0s 

Epoch 6/50
721/721 [==============================] - 0s 58us/step - loss: 1409.1484 - val_loss: 1287.2686
Epoch 7/50
721/721 [==============================] - 0s 56us/step - loss: 1384.2267 - val_loss: 1263.2057
Epoch 8/50
721/721 [==============================] - 0s 58us/step - loss: 1357.1412 - val_loss: 1237.3767
Epoch 9/50
721/721 [==============================] - 0s 57us/step - loss: 1328.3317 - val_loss: 1210.2426
Epoch 10/50
721/721 [==============================] - 0s 61us/step - loss: 1297.7584 - val_loss: 1181.5488
Epoch 11/50
721/721 [==============================] - 0s 57us/step - loss: 1265.9134 - val_loss: 1151.1274
Epoch 12/50
721/721 [==============================] - 0s 57us/step - loss: 1231.4277 - val_loss: 1120.2731
Epoch 13/50
721/721 [==============================] - 0s 58us/step - loss: 1196.4532 - val_loss: 1087.2057
Epoch 14/50
721/721 [==============================] - 0s 60us/step - loss: 1159.5126 - val_loss: 1052.6240
Epoch 15/50
721/721 [===========

721/721 [==============================] - 0s 64us/step - loss: 745.3132 - val_loss: 698.2926
Epoch 33/50
721/721 [==============================] - 0s 66us/step - loss: 715.4442 - val_loss: 671.7770
Epoch 34/50
721/721 [==============================] - 0s 63us/step - loss: 686.6192 - val_loss: 646.0619
Epoch 35/50
721/721 [==============================] - 0s 64us/step - loss: 658.4873 - val_loss: 621.4580
Epoch 36/50
721/721 [==============================] - 0s 67us/step - loss: 631.4354 - val_loss: 597.5230
Epoch 37/50
721/721 [==============================] - 0s 66us/step - loss: 605.1700 - val_loss: 574.5421
Epoch 38/50
721/721 [==============================] - 0s 64us/step - loss: 579.8910 - val_loss: 552.5363
Epoch 39/50
721/721 [==============================] - 0s 63us/step - loss: 555.8920 - val_loss: 531.2876
Epoch 40/50
721/721 [==============================] - 0s 63us/step - loss: 532.6671 - val_loss: 510.8833
Epoch 41/50
721/721 [==============================] - 0s 

Epoch 8/50
721/721 [==============================] - 0s 59us/step - loss: 1475.8589 - val_loss: 1355.9035
Epoch 9/50
721/721 [==============================] - 0s 58us/step - loss: 1455.6163 - val_loss: 1336.5363
Epoch 10/50
721/721 [==============================] - 0s 58us/step - loss: 1434.2043 - val_loss: 1316.5617
Epoch 11/50
721/721 [==============================] - 0s 58us/step - loss: 1411.8704 - val_loss: 1295.5465
Epoch 12/50
721/721 [==============================] - 0s 60us/step - loss: 1388.1655 - val_loss: 1273.7712
Epoch 13/50
721/721 [==============================] - 0s 58us/step - loss: 1363.8773 - val_loss: 1250.7319
Epoch 14/50
721/721 [==============================] - 0s 58us/step - loss: 1337.7061 - val_loss: 1227.6437
Epoch 15/50
721/721 [==============================] - 0s 58us/step - loss: 1311.2235 - val_loss: 1203.0469
Epoch 16/50
721/721 [==============================] - 0s 60us/step - loss: 1283.4493 - val_loss: 1177.6954
Epoch 17/50
721/721 [=========

721/721 [==============================] - 0s 59us/step - loss: 829.3042 - val_loss: 756.7852
Epoch 35/50
721/721 [==============================] - 0s 63us/step - loss: 799.4531 - val_loss: 731.1461
Epoch 36/50
721/721 [==============================] - 0s 66us/step - loss: 771.1926 - val_loss: 705.3776
Epoch 37/50
721/721 [==============================] - 0s 68us/step - loss: 742.8549 - val_loss: 680.6147
Epoch 38/50
721/721 [==============================] - 0s 66us/step - loss: 714.9502 - val_loss: 657.1054
Epoch 39/50
721/721 [==============================] - 0s 66us/step - loss: 688.5785 - val_loss: 633.3936
Epoch 40/50
721/721 [==============================] - 0s 66us/step - loss: 662.6639 - val_loss: 610.5209
Epoch 41/50
721/721 [==============================] - 0s 70us/step - loss: 637.3103 - val_loss: 588.9348
Epoch 42/50
721/721 [==============================] - 0s 70us/step - loss: 613.1405 - val_loss: 567.6905
Epoch 43/50
721/721 [==============================] - 0s 

Epoch 10/50
721/721 [==============================] - 0s 60us/step - loss: 1501.6343 - val_loss: 1382.2381
Epoch 11/50
721/721 [==============================] - 0s 59us/step - loss: 1484.3627 - val_loss: 1366.0738
Epoch 12/50
721/721 [==============================] - 0s 61us/step - loss: 1465.8336 - val_loss: 1349.5102
Epoch 13/50
721/721 [==============================] - 0s 58us/step - loss: 1446.6511 - val_loss: 1332.1710
Epoch 14/50
721/721 [==============================] - 0s 58us/step - loss: 1426.2704 - val_loss: 1314.0583
Epoch 15/50
721/721 [==============================] - 0s 60us/step - loss: 1405.1984 - val_loss: 1295.0251
Epoch 16/50
721/721 [==============================] - 0s 61us/step - loss: 1383.1580 - val_loss: 1275.2302
Epoch 17/50
721/721 [==============================] - 0s 59us/step - loss: 1360.3220 - val_loss: 1255.1238
Epoch 18/50
721/721 [==============================] - 0s 59us/step - loss: 1336.5659 - val_loss: 1234.4855
Epoch 19/50
721/721 [=======

721/721 [==============================] - 0s 64us/step - loss: 467.8448 - val_loss: 425.5060
Epoch 37/50
721/721 [==============================] - 0s 63us/step - loss: 443.5529 - val_loss: 405.1859
Epoch 38/50
721/721 [==============================] - 0s 65us/step - loss: 420.9093 - val_loss: 385.7901
Epoch 39/50
721/721 [==============================] - 0s 64us/step - loss: 399.8134 - val_loss: 367.8025
Epoch 40/50
721/721 [==============================] - 0s 64us/step - loss: 380.3497 - val_loss: 350.8610
Epoch 41/50
721/721 [==============================] - 0s 63us/step - loss: 362.0449 - val_loss: 335.4378
Epoch 42/50
721/721 [==============================] - 0s 63us/step - loss: 345.1961 - val_loss: 321.4212
Epoch 43/50
721/721 [==============================] - 0s 60us/step - loss: 330.0658 - val_loss: 308.3838
Epoch 44/50
721/721 [==============================] - 0s 62us/step - loss: 316.0470 - val_loss: 296.5079
Epoch 45/50
721/721 [==============================] - 0s 

Epoch 12/50
721/721 [==============================] - 0s 62us/step - loss: 1356.1546 - val_loss: 1246.7645
Epoch 13/50
721/721 [==============================] - 0s 62us/step - loss: 1331.6453 - val_loss: 1224.3255
Epoch 14/50
721/721 [==============================] - 0s 57us/step - loss: 1306.2594 - val_loss: 1201.3463
Epoch 15/50
721/721 [==============================] - 0s 58us/step - loss: 1280.0553 - val_loss: 1177.7748
Epoch 16/50
721/721 [==============================] - 0s 57us/step - loss: 1253.3282 - val_loss: 1153.2702
Epoch 17/50
721/721 [==============================] - 0s 58us/step - loss: 1225.8390 - val_loss: 1128.3812
Epoch 18/50
721/721 [==============================] - 0s 65us/step - loss: 1197.9691 - val_loss: 1103.3508
Epoch 19/50
721/721 [==============================] - 0s 64us/step - loss: 1169.4778 - val_loss: 1078.0450
Epoch 20/50
721/721 [==============================] - 0s 66us/step - loss: 1140.6873 - val_loss: 1052.1633
Epoch 21/50
721/721 [=======

721/721 [==============================] - 0s 70us/step - loss: 704.5169 - val_loss: 648.7100
Epoch 39/50
721/721 [==============================] - 0s 68us/step - loss: 677.0197 - val_loss: 624.9671
Epoch 40/50
721/721 [==============================] - 0s 68us/step - loss: 650.3730 - val_loss: 601.8855
Epoch 41/50
721/721 [==============================] - 0s 67us/step - loss: 624.3962 - val_loss: 579.6722
Epoch 42/50
721/721 [==============================] - 0s 68us/step - loss: 599.3056 - val_loss: 557.7957
Epoch 43/50
721/721 [==============================] - 0s 65us/step - loss: 575.0403 - val_loss: 536.5276
Epoch 44/50
721/721 [==============================] - 0s 63us/step - loss: 551.4271 - val_loss: 516.0193
Epoch 45/50
721/721 [==============================] - 0s 64us/step - loss: 528.6024 - val_loss: 496.7804
Epoch 46/50
721/721 [==============================] - 0s 64us/step - loss: 506.8440 - val_loss: 477.7280
Epoch 47/50
721/721 [==============================] - 0s 

721/721 [==============================] - 0s 59us/step - loss: 1318.7244 - val_loss: 1205.7197
Epoch 14/50
721/721 [==============================] - 0s 63us/step - loss: 1290.8767 - val_loss: 1179.5819
Epoch 15/50
721/721 [==============================] - 0s 58us/step - loss: 1260.9514 - val_loss: 1152.9031
Epoch 16/50
721/721 [==============================] - 0s 58us/step - loss: 1230.3970 - val_loss: 1123.5889
Epoch 17/50
721/721 [==============================] - 0s 59us/step - loss: 1197.8849 - val_loss: 1093.7146
Epoch 18/50
721/721 [==============================] - 0s 60us/step - loss: 1164.7506 - val_loss: 1062.9897
Epoch 19/50
721/721 [==============================] - 0s 58us/step - loss: 1130.5656 - val_loss: 1031.8970
Epoch 20/50
721/721 [==============================] - 0s 58us/step - loss: 1095.7086 - val_loss: 999.9995
Epoch 21/50
721/721 [==============================] - 0s 58us/step - loss: 1060.4485 - val_loss: 967.2082
Epoch 22/50
721/721 [=====================

721/721 [==============================] - 0s 61us/step - loss: 602.5286 - val_loss: 553.9344
Epoch 40/50
721/721 [==============================] - 0s 59us/step - loss: 574.1702 - val_loss: 529.6834
Epoch 41/50
721/721 [==============================] - 0s 63us/step - loss: 547.4855 - val_loss: 505.7183
Epoch 42/50
721/721 [==============================] - 0s 60us/step - loss: 521.0676 - val_loss: 483.3265
Epoch 43/50
721/721 [==============================] - 0s 59us/step - loss: 496.4353 - val_loss: 461.4223
Epoch 44/50
721/721 [==============================] - 0s 61us/step - loss: 472.5152 - val_loss: 440.8231
Epoch 45/50
721/721 [==============================] - 0s 59us/step - loss: 450.1770 - val_loss: 421.1847
Epoch 46/50
721/721 [==============================] - 0s 59us/step - loss: 429.0451 - val_loss: 402.7307
Epoch 47/50
721/721 [==============================] - 0s 59us/step - loss: 408.9788 - val_loss: 385.9568
Epoch 48/50
721/721 [==============================] - 0s 

Epoch 15/50
721/721 [==============================] - 0s 59us/step - loss: 1254.9416 - val_loss: 1134.4529
Epoch 16/50
721/721 [==============================] - 0s 60us/step - loss: 1220.5253 - val_loss: 1101.6719
Epoch 17/50
721/721 [==============================] - 0s 57us/step - loss: 1184.6125 - val_loss: 1068.3767
Epoch 18/50
721/721 [==============================] - 0s 58us/step - loss: 1147.8844 - val_loss: 1034.3696
Epoch 19/50
721/721 [==============================] - 0s 58us/step - loss: 1110.2583 - val_loss: 999.5806
Epoch 20/50
721/721 [==============================] - 0s 59us/step - loss: 1071.8536 - val_loss: 964.4301
Epoch 21/50
721/721 [==============================] - 0s 58us/step - loss: 1032.9801 - val_loss: 929.0581
Epoch 22/50
721/721 [==============================] - 0s 57us/step - loss: 993.7059 - val_loss: 893.2428
Epoch 23/50
721/721 [==============================] - 0s 58us/step - loss: 954.6464 - val_loss: 857.7005
Epoch 24/50
721/721 [==============

721/721 [==============================] - 0s 57us/step - loss: 464.8629 - val_loss: 437.6721
Epoch 42/50
721/721 [==============================] - 0s 60us/step - loss: 445.8806 - val_loss: 420.2905
Epoch 43/50
721/721 [==============================] - 0s 58us/step - loss: 427.8337 - val_loss: 404.0680
Epoch 44/50
721/721 [==============================] - 0s 58us/step - loss: 410.7187 - val_loss: 388.5785
Epoch 45/50
721/721 [==============================] - 0s 58us/step - loss: 394.7505 - val_loss: 374.0261
Epoch 46/50
721/721 [==============================] - 0s 57us/step - loss: 379.6409 - val_loss: 360.4836
Epoch 47/50
721/721 [==============================] - 0s 57us/step - loss: 365.8166 - val_loss: 347.2160
Epoch 48/50
721/721 [==============================] - 0s 57us/step - loss: 352.2533 - val_loss: 335.3971
Epoch 49/50
721/721 [==============================] - 0s 58us/step - loss: 340.2870 - val_loss: 323.8570
Epoch 50/50
721/721 [==============================] - 0s 

Epoch 17/50
721/721 [==============================] - 0s 58us/step - loss: 1110.5455 - val_loss: 1033.6756
Epoch 18/50
721/721 [==============================] - 0s 57us/step - loss: 1075.9724 - val_loss: 1003.4541
Epoch 19/50
721/721 [==============================] - 0s 57us/step - loss: 1041.3978 - val_loss: 972.4819
Epoch 20/50
721/721 [==============================] - 0s 57us/step - loss: 1006.2485 - val_loss: 941.1389
Epoch 21/50
721/721 [==============================] - 0s 59us/step - loss: 971.1390 - val_loss: 909.5646
Epoch 22/50
721/721 [==============================] - 0s 57us/step - loss: 935.7092 - val_loss: 878.7546
Epoch 23/50
721/721 [==============================] - 0s 57us/step - loss: 900.9769 - val_loss: 847.2806
Epoch 24/50
721/721 [==============================] - 0s 57us/step - loss: 866.0315 - val_loss: 816.4532
Epoch 25/50
721/721 [==============================] - 0s 57us/step - loss: 831.7719 - val_loss: 786.2132
Epoch 26/50
721/721 [===================

721/721 [==============================] - 0s 57us/step - loss: 484.2570 - val_loss: 454.3340
Epoch 44/50
721/721 [==============================] - 0s 57us/step - loss: 461.9956 - val_loss: 433.6737
Epoch 45/50
721/721 [==============================] - 0s 57us/step - loss: 440.5651 - val_loss: 414.3189
Epoch 46/50
721/721 [==============================] - 0s 58us/step - loss: 420.2105 - val_loss: 395.9592
Epoch 47/50
721/721 [==============================] - 0s 57us/step - loss: 401.1830 - val_loss: 378.6042
Epoch 48/50
721/721 [==============================] - 0s 57us/step - loss: 383.1547 - val_loss: 362.5885
Epoch 49/50
721/721 [==============================] - 0s 58us/step - loss: 366.4612 - val_loss: 347.5364
Epoch 50/50
721/721 [==============================] - 0s 57us/step - loss: 350.8328 - val_loss: 333.7629
Sample 29
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 625us/step - loss: 1545.5231 - val_loss: 1416.2869


Epoch 19/50
721/721 [==============================] - 0s 56us/step - loss: 1193.4946 - val_loss: 1088.3534
Epoch 20/50
721/721 [==============================] - 0s 56us/step - loss: 1157.8419 - val_loss: 1054.8582
Epoch 21/50
721/721 [==============================] - 0s 55us/step - loss: 1120.7129 - val_loss: 1020.8362
Epoch 22/50
721/721 [==============================] - 0s 54us/step - loss: 1082.6732 - val_loss: 985.5160
Epoch 23/50
721/721 [==============================] - 0s 56us/step - loss: 1043.7170 - val_loss: 950.2612
Epoch 24/50
721/721 [==============================] - 0s 56us/step - loss: 1004.3325 - val_loss: 914.4802
Epoch 25/50
721/721 [==============================] - 0s 56us/step - loss: 964.5716 - val_loss: 878.4194
Epoch 26/50
721/721 [==============================] - 0s 56us/step - loss: 924.5226 - val_loss: 842.2728
Epoch 27/50
721/721 [==============================] - 0s 56us/step - loss: 884.2467 - val_loss: 806.2296
Epoch 28/50
721/721 [================

721/721 [==============================] - 0s 60us/step - loss: 507.4011 - val_loss: 471.8110
Epoch 46/50
721/721 [==============================] - 0s 57us/step - loss: 484.4595 - val_loss: 450.9742
Epoch 47/50
721/721 [==============================] - 0s 58us/step - loss: 462.4024 - val_loss: 431.6461
Epoch 48/50
721/721 [==============================] - 0s 58us/step - loss: 441.9160 - val_loss: 413.6596
Epoch 49/50
721/721 [==============================] - 0s 57us/step - loss: 422.7666 - val_loss: 396.7886
Epoch 50/50
721/721 [==============================] - 0s 58us/step - loss: 404.6803 - val_loss: 381.6115
Sample 32
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 616us/step - loss: 1577.9952 - val_loss: 1449.1462
Epoch 2/50
721/721 [==============================] - 0s 56us/step - loss: 1560.3989 - val_loss: 1432.4928
Epoch 3/50
721/721 [==============================] - 0s 57us/step - loss: 1542.1616 - val_loss: 1415.307

721/721 [==============================] - 0s 117us/step - loss: 1314.5949 - val_loss: 1204.8640
Epoch 21/50
721/721 [==============================] - 0s 118us/step - loss: 1290.7369 - val_loss: 1182.3852
Epoch 22/50
721/721 [==============================] - 0s 118us/step - loss: 1266.1832 - val_loss: 1159.3622
Epoch 23/50
721/721 [==============================] - 0s 122us/step - loss: 1241.1292 - val_loss: 1135.8754
Epoch 24/50
721/721 [==============================] - 0s 118us/step - loss: 1215.4159 - val_loss: 1111.5984
Epoch 25/50
721/721 [==============================] - 0s 118us/step - loss: 1189.0693 - val_loss: 1087.4617
Epoch 26/50
721/721 [==============================] - 0s 116us/step - loss: 1162.7719 - val_loss: 1062.6673
Epoch 27/50
721/721 [==============================] - 0s 119us/step - loss: 1135.8991 - val_loss: 1037.6959
Epoch 28/50
721/721 [==============================] - 0s 119us/step - loss: 1108.7676 - val_loss: 1012.5496
Epoch 29/50
721/721 [==========

721/721 [==============================] - 0s 57us/step - loss: 435.1347 - val_loss: 424.9954
Epoch 47/50
721/721 [==============================] - 0s 58us/step - loss: 419.0768 - val_loss: 411.3679
Epoch 48/50
721/721 [==============================] - 0s 56us/step - loss: 404.2863 - val_loss: 398.1159
Epoch 49/50
721/721 [==============================] - 0s 56us/step - loss: 390.2725 - val_loss: 385.8847
Epoch 50/50
721/721 [==============================] - 0s 56us/step - loss: 376.8929 - val_loss: 374.3955
Sample 35
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 622us/step - loss: 1575.1418 - val_loss: 1446.1950
Epoch 2/50
721/721 [==============================] - 0s 61us/step - loss: 1558.2090 - val_loss: 1430.0219
Epoch 3/50
721/721 [==============================] - 0s 61us/step - loss: 1540.7871 - val_loss: 1413.0928
Epoch 4/50
721/721 [==============================] - 0s 60us/step - loss: 1522.4904 - val_loss: 1395.64

721/721 [==============================] - 0s 71us/step - loss: 1294.1855 - val_loss: 1182.0005
Epoch 22/50
721/721 [==============================] - 0s 66us/step - loss: 1270.9236 - val_loss: 1160.2263
Epoch 23/50
721/721 [==============================] - 0s 66us/step - loss: 1246.9609 - val_loss: 1138.3043
Epoch 24/50
721/721 [==============================] - 0s 62us/step - loss: 1222.8087 - val_loss: 1116.0802
Epoch 25/50
721/721 [==============================] - 0s 61us/step - loss: 1198.3271 - val_loss: 1093.2835
Epoch 26/50
721/721 [==============================] - 0s 62us/step - loss: 1173.4023 - val_loss: 1070.3995
Epoch 27/50
721/721 [==============================] - 0s 62us/step - loss: 1148.1296 - val_loss: 1047.3402
Epoch 28/50
721/721 [==============================] - 0s 63us/step - loss: 1122.7385 - val_loss: 1024.3515
Epoch 29/50
721/721 [==============================] - 0s 61us/step - loss: 1097.1957 - val_loss: 1001.2422
Epoch 30/50
721/721 [===================

721/721 [==============================] - 0s 58us/step - loss: 417.1944 - val_loss: 384.9205
Epoch 48/50
721/721 [==============================] - 0s 59us/step - loss: 396.4230 - val_loss: 367.0980
Epoch 49/50
721/721 [==============================] - 0s 58us/step - loss: 377.2453 - val_loss: 350.7383
Epoch 50/50
721/721 [==============================] - 0s 57us/step - loss: 359.4454 - val_loss: 335.9349
Sample 38
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 638us/step - loss: 1590.3218 - val_loss: 1454.7305
Epoch 2/50
721/721 [==============================] - 0s 59us/step - loss: 1572.3711 - val_loss: 1438.2346
Epoch 3/50
721/721 [==============================] - 0s 59us/step - loss: 1554.0699 - val_loss: 1421.6345
Epoch 4/50
721/721 [==============================] - 0s 65us/step - loss: 1535.5602 - val_loss: 1404.5722
Epoch 5/50
721/721 [==============================] - 0s 66us/step - loss: 1516.5633 - val_loss: 1386.8

721/721 [==============================] - 0s 57us/step - loss: 1114.6332 - val_loss: 995.4693
Epoch 23/50
721/721 [==============================] - 0s 56us/step - loss: 1081.5393 - val_loss: 964.9181
Epoch 24/50
721/721 [==============================] - 0s 57us/step - loss: 1048.4739 - val_loss: 933.9705
Epoch 25/50
721/721 [==============================] - 0s 57us/step - loss: 1014.3635 - val_loss: 903.8682
Epoch 26/50
721/721 [==============================] - 0s 57us/step - loss: 981.0205 - val_loss: 872.6548
Epoch 27/50
721/721 [==============================] - 0s 58us/step - loss: 946.9867 - val_loss: 842.0963
Epoch 28/50
721/721 [==============================] - 0s 58us/step - loss: 913.1358 - val_loss: 811.4752
Epoch 29/50
721/721 [==============================] - 0s 57us/step - loss: 880.1745 - val_loss: 780.5292
Epoch 30/50
721/721 [==============================] - 0s 58us/step - loss: 846.5540 - val_loss: 751.3569
Epoch 31/50
721/721 [==============================] -

721/721 [==============================] - 0s 66us/step - loss: 494.6031 - val_loss: 463.0903
Epoch 49/50
721/721 [==============================] - 0s 65us/step - loss: 475.7176 - val_loss: 446.0079
Epoch 50/50
721/721 [==============================] - 0s 66us/step - loss: 457.4243 - val_loss: 430.3067
Sample 41
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 624us/step - loss: 1540.3298 - val_loss: 1412.0006
Epoch 2/50
721/721 [==============================] - 0s 59us/step - loss: 1523.4126 - val_loss: 1395.5688
Epoch 3/50
721/721 [==============================] - 0s 59us/step - loss: 1505.8458 - val_loss: 1378.5811
Epoch 4/50
721/721 [==============================] - 0s 57us/step - loss: 1487.5959 - val_loss: 1360.7324
Epoch 5/50
721/721 [==============================] - 0s 58us/step - loss: 1468.1921 - val_loss: 1342.1286
Epoch 6/50
721/721 [==============================] - 0s 58us/step - loss: 1447.9511 - val_loss: 1322.

721/721 [==============================] - 0s 67us/step - loss: 1028.5233 - val_loss: 929.5755
Epoch 24/50
721/721 [==============================] - 0s 68us/step - loss: 991.5062 - val_loss: 896.3221
Epoch 25/50
721/721 [==============================] - 0s 65us/step - loss: 955.2594 - val_loss: 862.5961
Epoch 26/50
721/721 [==============================] - 0s 60us/step - loss: 918.4278 - val_loss: 829.1803
Epoch 27/50
721/721 [==============================] - 0s 59us/step - loss: 881.8729 - val_loss: 795.5608
Epoch 28/50
721/721 [==============================] - 0s 61us/step - loss: 845.2116 - val_loss: 762.3890
Epoch 29/50
721/721 [==============================] - 0s 60us/step - loss: 809.2774 - val_loss: 729.1723
Epoch 30/50
721/721 [==============================] - 0s 59us/step - loss: 773.5073 - val_loss: 696.8126
Epoch 31/50
721/721 [==============================] - 0s 59us/step - loss: 738.4944 - val_loss: 665.4064
Epoch 32/50
721/721 [==============================] - 0s

721/721 [==============================] - 0s 65us/step - loss: 549.3027 - val_loss: 508.4885
Epoch 50/50
721/721 [==============================] - 0s 64us/step - loss: 525.6715 - val_loss: 487.7113
Sample 44
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 0s 658us/step - loss: 1557.4667 - val_loss: 1430.1539
Epoch 2/50
721/721 [==============================] - 0s 63us/step - loss: 1541.5442 - val_loss: 1415.1224
Epoch 3/50
721/721 [==============================] - 0s 62us/step - loss: 1525.1350 - val_loss: 1399.7025
Epoch 4/50
721/721 [==============================] - 0s 62us/step - loss: 1508.2116 - val_loss: 1383.6309
Epoch 5/50
721/721 [==============================] - 0s 66us/step - loss: 1490.3963 - val_loss: 1366.9455
Epoch 6/50
721/721 [==============================] - 0s 58us/step - loss: 1471.6337 - val_loss: 1349.2857
Epoch 7/50
721/721 [==============================] - 0s 58us/step - loss: 1451.8664 - val_loss: 1330

721/721 [==============================] - 0s 57us/step - loss: 976.1739 - val_loss: 889.2328
Epoch 25/50
721/721 [==============================] - 0s 57us/step - loss: 940.3886 - val_loss: 856.7668
Epoch 26/50
721/721 [==============================] - 0s 63us/step - loss: 904.4755 - val_loss: 825.0577
Epoch 27/50
721/721 [==============================] - 0s 63us/step - loss: 868.8020 - val_loss: 794.1223
Epoch 28/50
721/721 [==============================] - 0s 65us/step - loss: 833.9945 - val_loss: 763.1777
Epoch 29/50
721/721 [==============================] - 0s 60us/step - loss: 799.2470 - val_loss: 733.0964
Epoch 30/50
721/721 [==============================] - 0s 60us/step - loss: 765.6852 - val_loss: 703.5499
Epoch 31/50
721/721 [==============================] - 0s 60us/step - loss: 732.4649 - val_loss: 675.1656
Epoch 32/50
721/721 [==============================] - 0s 59us/step - loss: 700.7653 - val_loss: 647.4312
Epoch 33/50
721/721 [==============================] - 0s 

721/721 [==============================] - 0s 65us/step - loss: 373.8102 - val_loss: 351.9131
Sample 47
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 1s 703us/step - loss: 1591.0285 - val_loss: 1468.0186
Epoch 2/50
721/721 [==============================] - 0s 64us/step - loss: 1571.7538 - val_loss: 1450.1131
Epoch 3/50
721/721 [==============================] - 0s 61us/step - loss: 1552.9167 - val_loss: 1432.5658
Epoch 4/50
721/721 [==============================] - 0s 60us/step - loss: 1534.5055 - val_loss: 1415.4249
Epoch 5/50
721/721 [==============================] - 0s 57us/step - loss: 1516.2694 - val_loss: 1397.9306
Epoch 6/50
721/721 [==============================] - 0s 59us/step - loss: 1497.6578 - val_loss: 1380.1724
Epoch 7/50
721/721 [==============================] - 0s 59us/step - loss: 1478.7811 - val_loss: 1362.1280
Epoch 8/50
721/721 [==============================] - 0s 62us/step - loss: 1459.2260 - val_loss: 134

721/721 [==============================] - 0s 58us/step - loss: 1311.0202 - val_loss: 1218.0617
Epoch 26/50
721/721 [==============================] - 0s 59us/step - loss: 1289.5812 - val_loss: 1199.9825
Epoch 27/50
721/721 [==============================] - 0s 58us/step - loss: 1268.5193 - val_loss: 1181.1725
Epoch 28/50
721/721 [==============================] - 0s 59us/step - loss: 1246.4181 - val_loss: 1163.2305
Epoch 29/50
721/721 [==============================] - 0s 58us/step - loss: 1225.0178 - val_loss: 1144.4441
Epoch 30/50
721/721 [==============================] - 0s 59us/step - loss: 1203.0844 - val_loss: 1125.3826
Epoch 31/50
721/721 [==============================] - 0s 61us/step - loss: 1180.7755 - val_loss: 1106.5263
Epoch 32/50
721/721 [==============================] - 0s 58us/step - loss: 1158.5445 - val_loss: 1087.6011
Epoch 33/50
721/721 [==============================] - 0s 59us/step - loss: 1136.0469 - val_loss: 1068.6315
Epoch 34/50
721/721 [===================

In [44]:
#Calculate mean and standard deviation of RMSE list

mean = sum(eval_list) / len(eval_list) 
variance = sum([((x - mean) ** 2) for x in eval_list]) / len(eval_list) 
st_dev = variance ** 0.5


print("The Mean of the RMSE list is : " +str(mean)+ " and the Standard deviation is : " + str(st_dev)) 



The Mean of the RMSE list is : 352.31027602704967 and the Standard deviation is : 95.44764127258529


When looking at the means, we can see that by normalizing the data, we were able to decrease or RMSE form about 535 to  352!


### Experimenting with More Epochs

C) Increase the number of Epochs to 100

In [45]:
#Establish parameters
EPochs = 100
samples = 50

In [46]:
#Predict and evaluate

#Starting list that will contain RMSE scores for each sample
eval_list = []

for i in range(samples):
    print("Sample " + str(i))
    #Split data into test and train over each iteration
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=.3, random_state=99)

    #Re-build NN
    model = regression_model()
    
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=EPochs, verbose=1)
    eval_list.append(model.evaluate(X_test, y_test, verbose=0))

    

Sample 0
Train on 721 samples, validate on 309 samples
Epoch 1/100
721/721 [==============================] - 0s 622us/step - loss: 1587.2216 - val_loss: 1450.4798
Epoch 2/100
721/721 [==============================] - 0s 63us/step - loss: 1570.8520 - val_loss: 1434.8663
Epoch 3/100
721/721 [==============================] - 0s 62us/step - loss: 1554.2806 - val_loss: 1418.9382
Epoch 4/100
721/721 [==============================] - 0s 65us/step - loss: 1537.2058 - val_loss: 1402.3681
Epoch 5/100
721/721 [==============================] - 0s 65us/step - loss: 1519.7765 - val_loss: 1384.8980
Epoch 6/100
721/721 [==============================] - 0s 64us/step - loss: 1501.1404 - val_loss: 1367.1494
Epoch 7/100
721/721 [==============================] - 0s 59us/step - loss: 1482.0334 - val_loss: 1347.6501
Epoch 8/100
721/721 [==============================] - 0s 58us/step - loss: 1461.3369 - val_loss: 1327.7757
Epoch 9/100
721/721 [==============================] - 0s 59us/step - loss: 1440

721/721 [==============================] - 0s 66us/step - loss: 181.7462 - val_loss: 187.8622
Epoch 77/100
721/721 [==============================] - 0s 63us/step - loss: 179.2870 - val_loss: 186.2528
Epoch 78/100
721/721 [==============================] - 0s 58us/step - loss: 177.2112 - val_loss: 184.6671
Epoch 79/100
721/721 [==============================] - 0s 58us/step - loss: 175.2161 - val_loss: 183.0951
Epoch 80/100
721/721 [==============================] - 0s 59us/step - loss: 173.2557 - val_loss: 181.6351
Epoch 81/100
721/721 [==============================] - 0s 57us/step - loss: 171.3429 - val_loss: 180.1487
Epoch 82/100
721/721 [==============================] - 0s 57us/step - loss: 169.5306 - val_loss: 178.7598
Epoch 83/100
721/721 [==============================] - 0s 58us/step - loss: 167.8546 - val_loss: 177.4475
Epoch 84/100
721/721 [==============================] - 0s 58us/step - loss: 166.0536 - val_loss: 176.1414
Epoch 85/100
721/721 [============================

721/721 [==============================] - 0s 57us/step - loss: 461.3171 - val_loss: 435.8843
Epoch 52/100
721/721 [==============================] - 0s 59us/step - loss: 441.6000 - val_loss: 419.7950
Epoch 53/100
721/721 [==============================] - 0s 57us/step - loss: 423.2355 - val_loss: 404.5704
Epoch 54/100
721/721 [==============================] - 0s 57us/step - loss: 406.1035 - val_loss: 389.8184
Epoch 55/100
721/721 [==============================] - 0s 55us/step - loss: 389.6580 - val_loss: 376.2339
Epoch 56/100
721/721 [==============================] - 0s 60us/step - loss: 374.2488 - val_loss: 363.1031
Epoch 57/100
721/721 [==============================] - 0s 58us/step - loss: 359.8734 - val_loss: 350.8658
Epoch 58/100
721/721 [==============================] - 0s 57us/step - loss: 346.4845 - val_loss: 339.3392
Epoch 59/100
721/721 [==============================] - 0s 57us/step - loss: 333.8817 - val_loss: 328.5975
Epoch 60/100
721/721 [============================

Epoch 27/100
721/721 [==============================] - 0s 58us/step - loss: 921.7849 - val_loss: 846.7518
Epoch 28/100
721/721 [==============================] - 0s 58us/step - loss: 888.2444 - val_loss: 816.3907
Epoch 29/100
721/721 [==============================] - 0s 58us/step - loss: 854.7632 - val_loss: 786.4397
Epoch 30/100
721/721 [==============================] - 0s 58us/step - loss: 821.8562 - val_loss: 756.7491
Epoch 31/100
721/721 [==============================] - 0s 61us/step - loss: 789.6788 - val_loss: 727.5049
Epoch 32/100
721/721 [==============================] - 0s 62us/step - loss: 757.7404 - val_loss: 699.2198
Epoch 33/100
721/721 [==============================] - 0s 64us/step - loss: 726.7727 - val_loss: 671.0843
Epoch 34/100
721/721 [==============================] - 0s 63us/step - loss: 696.1983 - val_loss: 643.6615
Epoch 35/100
721/721 [==============================] - 0s 63us/step - loss: 666.2674 - val_loss: 616.9917
Epoch 36/100
721/721 [===============

721/721 [==============================] - 0s 57us/step - loss: 1607.2743 - val_loss: 1474.1943
Epoch 4/100
721/721 [==============================] - 0s 57us/step - loss: 1590.9609 - val_loss: 1459.0446
Epoch 5/100
721/721 [==============================] - 0s 57us/step - loss: 1575.2596 - val_loss: 1443.8640
Epoch 6/100
721/721 [==============================] - 0s 56us/step - loss: 1559.5616 - val_loss: 1428.9181
Epoch 7/100
721/721 [==============================] - 0s 58us/step - loss: 1543.8030 - val_loss: 1414.1146
Epoch 8/100
721/721 [==============================] - 0s 56us/step - loss: 1528.1459 - val_loss: 1398.8966
Epoch 9/100
721/721 [==============================] - 0s 58us/step - loss: 1512.1579 - val_loss: 1383.1158
Epoch 10/100
721/721 [==============================] - 0s 59us/step - loss: 1495.8151 - val_loss: 1367.0222
Epoch 11/100
721/721 [==============================] - 0s 64us/step - loss: 1478.9263 - val_loss: 1351.0823
Epoch 12/100
721/721 [================

721/721 [==============================] - 0s 57us/step - loss: 215.2192 - val_loss: 222.6283
Epoch 80/100
721/721 [==============================] - 0s 56us/step - loss: 211.7917 - val_loss: 219.3022
Epoch 81/100
721/721 [==============================] - 0s 60us/step - loss: 208.4258 - val_loss: 216.2336
Epoch 82/100
721/721 [==============================] - 0s 58us/step - loss: 205.1853 - val_loss: 213.1495
Epoch 83/100
721/721 [==============================] - 0s 63us/step - loss: 202.0264 - val_loss: 210.4288
Epoch 84/100
721/721 [==============================] - 0s 62us/step - loss: 199.0176 - val_loss: 207.4261
Epoch 85/100
721/721 [==============================] - 0s 70us/step - loss: 196.1622 - val_loss: 204.5703
Epoch 86/100
721/721 [==============================] - 0s 65us/step - loss: 193.3275 - val_loss: 201.9870
Epoch 87/100
721/721 [==============================] - 0s 65us/step - loss: 190.6597 - val_loss: 199.4295
Epoch 88/100
721/721 [============================

Epoch 55/100
721/721 [==============================] - 0s 68us/step - loss: 290.0380 - val_loss: 290.7845
Epoch 56/100
721/721 [==============================] - 0s 67us/step - loss: 283.3065 - val_loss: 284.3576
Epoch 57/100
721/721 [==============================] - 0s 67us/step - loss: 276.7899 - val_loss: 278.6299
Epoch 58/100
721/721 [==============================] - 0s 68us/step - loss: 270.7493 - val_loss: 272.7411
Epoch 59/100
721/721 [==============================] - 0s 66us/step - loss: 264.9231 - val_loss: 267.3031
Epoch 60/100
721/721 [==============================] - 0s 66us/step - loss: 259.6106 - val_loss: 262.1707
Epoch 61/100
721/721 [==============================] - 0s 63us/step - loss: 254.4291 - val_loss: 257.4687
Epoch 62/100
721/721 [==============================] - 0s 63us/step - loss: 249.6419 - val_loss: 252.8798
Epoch 63/100
721/721 [==============================] - 0s 63us/step - loss: 245.1419 - val_loss: 248.3977
Epoch 64/100
721/721 [===============

721/721 [==============================] - 0s 58us/step - loss: 713.7354 - val_loss: 661.8912
Epoch 31/100
721/721 [==============================] - 0s 60us/step - loss: 681.6000 - val_loss: 633.2122
Epoch 32/100
721/721 [==============================] - 0s 58us/step - loss: 650.2396 - val_loss: 605.7053
Epoch 33/100
721/721 [==============================] - 0s 58us/step - loss: 620.0514 - val_loss: 579.3699
Epoch 34/100
721/721 [==============================] - 0s 56us/step - loss: 591.3416 - val_loss: 553.7506
Epoch 35/100
721/721 [==============================] - 0s 57us/step - loss: 563.7175 - val_loss: 529.7278
Epoch 36/100
721/721 [==============================] - 0s 57us/step - loss: 537.4392 - val_loss: 506.9376
Epoch 37/100
721/721 [==============================] - 0s 57us/step - loss: 512.7471 - val_loss: 484.9442
Epoch 38/100
721/721 [==============================] - 0s 57us/step - loss: 489.1731 - val_loss: 464.1566
Epoch 39/100
721/721 [============================

721/721 [==============================] - 0s 59us/step - loss: 1495.5190 - val_loss: 1372.1141
Epoch 7/100
721/721 [==============================] - 0s 59us/step - loss: 1478.7058 - val_loss: 1355.6800
Epoch 8/100
721/721 [==============================] - 0s 59us/step - loss: 1461.0590 - val_loss: 1338.1314
Epoch 9/100
721/721 [==============================] - 0s 58us/step - loss: 1442.1415 - val_loss: 1319.3774
Epoch 10/100
721/721 [==============================] - 0s 60us/step - loss: 1421.8781 - val_loss: 1299.4520
Epoch 11/100
721/721 [==============================] - 0s 59us/step - loss: 1400.0821 - val_loss: 1278.3356
Epoch 12/100
721/721 [==============================] - 0s 58us/step - loss: 1376.9377 - val_loss: 1255.1416
Epoch 13/100
721/721 [==============================] - 0s 59us/step - loss: 1351.6775 - val_loss: 1231.1373
Epoch 14/100
721/721 [==============================] - 0s 58us/step - loss: 1325.1337 - val_loss: 1205.5775
Epoch 15/100
721/721 [=============

721/721 [==============================] - 0s 60us/step - loss: 164.8235 - val_loss: 167.2250
Epoch 83/100
721/721 [==============================] - 0s 61us/step - loss: 163.6849 - val_loss: 166.4417
Epoch 84/100
721/721 [==============================] - 0s 61us/step - loss: 162.4949 - val_loss: 165.4776
Epoch 85/100
721/721 [==============================] - 0s 60us/step - loss: 161.3869 - val_loss: 164.6275
Epoch 86/100
721/721 [==============================] - 0s 61us/step - loss: 160.2593 - val_loss: 163.6642
Epoch 87/100
721/721 [==============================] - 0s 67us/step - loss: 159.1459 - val_loss: 162.9269
Epoch 88/100
721/721 [==============================] - 0s 69us/step - loss: 158.0353 - val_loss: 162.1349
Epoch 89/100
721/721 [==============================] - 0s 67us/step - loss: 157.0127 - val_loss: 161.3288
Epoch 90/100
721/721 [==============================] - 0s 62us/step - loss: 155.9229 - val_loss: 160.5929
Epoch 91/100
721/721 [============================

Epoch 58/100
721/721 [==============================] - 0s 59us/step - loss: 224.7260 - val_loss: 230.6630
Epoch 59/100
721/721 [==============================] - 0s 57us/step - loss: 221.0685 - val_loss: 227.3802
Epoch 60/100
721/721 [==============================] - 0s 58us/step - loss: 217.7596 - val_loss: 224.1703
Epoch 61/100
721/721 [==============================] - 0s 57us/step - loss: 214.4785 - val_loss: 221.3304
Epoch 62/100
721/721 [==============================] - 0s 57us/step - loss: 211.5734 - val_loss: 218.7651
Epoch 63/100
721/721 [==============================] - 0s 58us/step - loss: 208.7904 - val_loss: 216.0624
Epoch 64/100
721/721 [==============================] - 0s 58us/step - loss: 206.0535 - val_loss: 213.6047
Epoch 65/100
721/721 [==============================] - 0s 57us/step - loss: 203.4669 - val_loss: 211.1688
Epoch 66/100
721/721 [==============================] - 0s 57us/step - loss: 201.0032 - val_loss: 208.7935
Epoch 67/100
721/721 [===============

Epoch 34/100
721/721 [==============================] - 0s 59us/step - loss: 574.1880 - val_loss: 539.1367
Epoch 35/100
721/721 [==============================] - 0s 60us/step - loss: 548.5588 - val_loss: 516.2420
Epoch 36/100
721/721 [==============================] - 0s 58us/step - loss: 523.6704 - val_loss: 494.9093
Epoch 37/100
721/721 [==============================] - 0s 58us/step - loss: 500.3536 - val_loss: 474.5284
Epoch 38/100
721/721 [==============================] - 0s 59us/step - loss: 478.0206 - val_loss: 455.0988
Epoch 39/100
721/721 [==============================] - 0s 59us/step - loss: 456.8159 - val_loss: 436.8650
Epoch 40/100
721/721 [==============================] - 0s 58us/step - loss: 436.9520 - val_loss: 419.5357
Epoch 41/100
721/721 [==============================] - 0s 58us/step - loss: 418.0236 - val_loss: 403.5004
Epoch 42/100
721/721 [==============================] - 0s 59us/step - loss: 400.4729 - val_loss: 388.2550
Epoch 43/100
721/721 [===============

Epoch 10/100
721/721 [==============================] - 0s 61us/step - loss: 1356.9738 - val_loss: 1245.5117
Epoch 11/100
721/721 [==============================] - 0s 59us/step - loss: 1329.8593 - val_loss: 1220.1617
Epoch 12/100
721/721 [==============================] - 0s 60us/step - loss: 1301.1348 - val_loss: 1192.9204
Epoch 13/100
721/721 [==============================] - 0s 59us/step - loss: 1270.3061 - val_loss: 1165.1837
Epoch 14/100
721/721 [==============================] - 0s 59us/step - loss: 1238.5090 - val_loss: 1135.1618
Epoch 15/100
721/721 [==============================] - 0s 58us/step - loss: 1205.0429 - val_loss: 1103.8199
Epoch 16/100
721/721 [==============================] - 0s 62us/step - loss: 1169.7115 - val_loss: 1071.7040
Epoch 17/100
721/721 [==============================] - 0s 59us/step - loss: 1133.6425 - val_loss: 1038.7030
Epoch 18/100
721/721 [==============================] - 0s 59us/step - loss: 1096.6505 - val_loss: 1004.8003
Epoch 19/100
721/72

721/721 [==============================] - 0s 58us/step - loss: 163.2985 - val_loss: 173.4683
Epoch 87/100
721/721 [==============================] - 0s 57us/step - loss: 161.7506 - val_loss: 172.1823
Epoch 88/100
721/721 [==============================] - 0s 56us/step - loss: 160.2474 - val_loss: 170.8066
Epoch 89/100
721/721 [==============================] - 0s 56us/step - loss: 158.7475 - val_loss: 169.5684
Epoch 90/100
721/721 [==============================] - 0s 57us/step - loss: 157.3140 - val_loss: 168.4171
Epoch 91/100
721/721 [==============================] - 0s 56us/step - loss: 155.9364 - val_loss: 167.0234
Epoch 92/100
721/721 [==============================] - 0s 56us/step - loss: 154.6425 - val_loss: 165.7799
Epoch 93/100
721/721 [==============================] - 0s 57us/step - loss: 153.2787 - val_loss: 164.6278
Epoch 94/100
721/721 [==============================] - 0s 56us/step - loss: 151.9875 - val_loss: 163.3739
Epoch 95/100
721/721 [============================

Epoch 62/100
721/721 [==============================] - 0s 60us/step - loss: 236.8387 - val_loss: 240.5490
Epoch 63/100
721/721 [==============================] - 0s 58us/step - loss: 231.8186 - val_loss: 236.3052
Epoch 64/100
721/721 [==============================] - 0s 60us/step - loss: 227.3284 - val_loss: 232.2981
Epoch 65/100
721/721 [==============================] - 0s 57us/step - loss: 223.1053 - val_loss: 228.6122
Epoch 66/100
721/721 [==============================] - 0s 57us/step - loss: 219.1552 - val_loss: 225.4512
Epoch 67/100
721/721 [==============================] - 0s 58us/step - loss: 215.6462 - val_loss: 222.3458
Epoch 68/100
721/721 [==============================] - 0s 60us/step - loss: 212.2715 - val_loss: 219.5602
Epoch 69/100
721/721 [==============================] - 0s 59us/step - loss: 209.2018 - val_loss: 217.0022
Epoch 70/100
721/721 [==============================] - 0s 59us/step - loss: 206.3525 - val_loss: 214.5317
Epoch 71/100
721/721 [===============

721/721 [==============================] - 0s 55us/step - loss: 696.0210 - val_loss: 647.6054
Epoch 38/100
721/721 [==============================] - 0s 57us/step - loss: 669.3153 - val_loss: 623.4601
Epoch 39/100
721/721 [==============================] - 0s 54us/step - loss: 643.3690 - val_loss: 599.5970
Epoch 40/100
721/721 [==============================] - 0s 55us/step - loss: 617.5460 - val_loss: 576.7299
Epoch 41/100
721/721 [==============================] - 0s 54us/step - loss: 592.6931 - val_loss: 553.3940
Epoch 42/100
721/721 [==============================] - 0s 55us/step - loss: 567.8468 - val_loss: 530.8682
Epoch 43/100
721/721 [==============================] - 0s 54us/step - loss: 543.8524 - val_loss: 509.1425
Epoch 44/100
721/721 [==============================] - 0s 55us/step - loss: 520.5377 - val_loss: 488.1739
Epoch 45/100
721/721 [==============================] - 0s 56us/step - loss: 498.3126 - val_loss: 467.3863
Epoch 46/100
721/721 [============================

721/721 [==============================] - 0s 59us/step - loss: 1429.0716 - val_loss: 1312.0823
Epoch 14/100
721/721 [==============================] - 0s 58us/step - loss: 1407.7737 - val_loss: 1291.6690
Epoch 15/100
721/721 [==============================] - 0s 61us/step - loss: 1385.4738 - val_loss: 1269.8224
Epoch 16/100
721/721 [==============================] - 0s 61us/step - loss: 1361.8400 - val_loss: 1247.4445
Epoch 17/100
721/721 [==============================] - 0s 62us/step - loss: 1337.8426 - val_loss: 1223.5051
Epoch 18/100
721/721 [==============================] - 0s 63us/step - loss: 1312.0326 - val_loss: 1199.9155
Epoch 19/100
721/721 [==============================] - 0s 61us/step - loss: 1286.1273 - val_loss: 1174.6199
Epoch 20/100
721/721 [==============================] - 0s 58us/step - loss: 1259.3620 - val_loss: 1148.8703
Epoch 21/100
721/721 [==============================] - 0s 59us/step - loss: 1231.6935 - val_loss: 1123.4037
Epoch 22/100
721/721 [==========

721/721 [==============================] - 0s 61us/step - loss: 167.3377 - val_loss: 176.3049
Epoch 90/100
721/721 [==============================] - 0s 61us/step - loss: 166.3454 - val_loss: 175.4403
Epoch 91/100
721/721 [==============================] - 0s 61us/step - loss: 165.3269 - val_loss: 174.6454
Epoch 92/100
721/721 [==============================] - 0s 62us/step - loss: 164.3691 - val_loss: 173.9531
Epoch 93/100
721/721 [==============================] - 0s 66us/step - loss: 163.4274 - val_loss: 173.2684
Epoch 94/100
721/721 [==============================] - 0s 64us/step - loss: 162.5013 - val_loss: 172.6600
Epoch 95/100
721/721 [==============================] - 0s 60us/step - loss: 161.6585 - val_loss: 171.9120
Epoch 96/100
721/721 [==============================] - 0s 58us/step - loss: 160.8265 - val_loss: 171.2966
Epoch 97/100
721/721 [==============================] - 0s 58us/step - loss: 159.9859 - val_loss: 170.7202
Epoch 98/100
721/721 [============================

Epoch 65/100
721/721 [==============================] - 0s 57us/step - loss: 257.8233 - val_loss: 266.9789
Epoch 66/100
721/721 [==============================] - 0s 66us/step - loss: 252.8161 - val_loss: 262.5963
Epoch 67/100
721/721 [==============================] - 0s 66us/step - loss: 248.0847 - val_loss: 258.6385
Epoch 68/100
721/721 [==============================] - 0s 66us/step - loss: 243.7421 - val_loss: 254.8221
Epoch 69/100
721/721 [==============================] - 0s 63us/step - loss: 239.6756 - val_loss: 251.2090
Epoch 70/100
721/721 [==============================] - 0s 59us/step - loss: 235.7578 - val_loss: 247.6858
Epoch 71/100
721/721 [==============================] - 0s 60us/step - loss: 232.0234 - val_loss: 244.5171
Epoch 72/100
721/721 [==============================] - 0s 61us/step - loss: 228.5960 - val_loss: 241.3584
Epoch 73/100
721/721 [==============================] - 0s 63us/step - loss: 225.2410 - val_loss: 238.4932
Epoch 74/100
721/721 [===============

721/721 [==============================] - 0s 63us/step - loss: 588.0788 - val_loss: 550.0221
Epoch 41/100
721/721 [==============================] - 0s 60us/step - loss: 565.6250 - val_loss: 531.1519
Epoch 42/100
721/721 [==============================] - 0s 60us/step - loss: 544.3832 - val_loss: 513.0543
Epoch 43/100
721/721 [==============================] - 0s 59us/step - loss: 524.2421 - val_loss: 495.2099
Epoch 44/100
721/721 [==============================] - 0s 59us/step - loss: 504.4790 - val_loss: 478.6811
Epoch 45/100
721/721 [==============================] - 0s 61us/step - loss: 486.0424 - val_loss: 462.7517
Epoch 46/100
721/721 [==============================] - 0s 59us/step - loss: 468.2663 - val_loss: 447.5806
Epoch 47/100
721/721 [==============================] - 0s 62us/step - loss: 451.2231 - val_loss: 433.4584
Epoch 48/100
721/721 [==============================] - 0s 59us/step - loss: 435.3219 - val_loss: 419.6034
Epoch 49/100
721/721 [============================

Epoch 16/100
721/721 [==============================] - 0s 56us/step - loss: 1265.9188 - val_loss: 1149.9287
Epoch 17/100
721/721 [==============================] - 0s 56us/step - loss: 1238.6612 - val_loss: 1124.3854
Epoch 18/100
721/721 [==============================] - 0s 58us/step - loss: 1210.6134 - val_loss: 1098.6347
Epoch 19/100
721/721 [==============================] - 0s 58us/step - loss: 1182.0176 - val_loss: 1072.2399
Epoch 20/100
721/721 [==============================] - 0s 57us/step - loss: 1152.9685 - val_loss: 1045.1286
Epoch 21/100
721/721 [==============================] - 0s 57us/step - loss: 1123.0441 - val_loss: 1018.1303
Epoch 22/100
721/721 [==============================] - 0s 57us/step - loss: 1092.7729 - val_loss: 990.3881
Epoch 23/100
721/721 [==============================] - 0s 56us/step - loss: 1061.9596 - val_loss: 962.8250
Epoch 24/100
721/721 [==============================] - 0s 56us/step - loss: 1031.3096 - val_loss: 935.2074
Epoch 25/100
721/721 [

721/721 [==============================] - 0s 57us/step - loss: 173.0290 - val_loss: 182.8185
Epoch 93/100
721/721 [==============================] - 0s 56us/step - loss: 171.4675 - val_loss: 181.3600
Epoch 94/100
721/721 [==============================] - 0s 56us/step - loss: 169.7667 - val_loss: 180.0009
Epoch 95/100
721/721 [==============================] - 0s 57us/step - loss: 168.1553 - val_loss: 178.6019
Epoch 96/100
721/721 [==============================] - 0s 56us/step - loss: 166.5055 - val_loss: 177.3193
Epoch 97/100
721/721 [==============================] - 0s 56us/step - loss: 164.9908 - val_loss: 176.0278
Epoch 98/100
721/721 [==============================] - 0s 57us/step - loss: 163.5839 - val_loss: 174.8772
Epoch 99/100
721/721 [==============================] - 0s 58us/step - loss: 162.1273 - val_loss: 173.6564
Epoch 100/100
721/721 [==============================] - 0s 58us/step - loss: 160.7933 - val_loss: 172.5332
Sample 16
Train on 721 samples, validate on 309 s

Epoch 68/100
721/721 [==============================] - 0s 60us/step - loss: 233.0091 - val_loss: 245.2944
Epoch 69/100
721/721 [==============================] - 0s 57us/step - loss: 228.6425 - val_loss: 241.1975
Epoch 70/100
721/721 [==============================] - 0s 58us/step - loss: 224.5669 - val_loss: 237.2161
Epoch 71/100
721/721 [==============================] - 0s 58us/step - loss: 220.6109 - val_loss: 233.2707
Epoch 72/100
721/721 [==============================] - 0s 57us/step - loss: 216.8749 - val_loss: 229.5859
Epoch 73/100
721/721 [==============================] - 0s 58us/step - loss: 213.0540 - val_loss: 226.2524
Epoch 74/100
721/721 [==============================] - 0s 59us/step - loss: 209.6882 - val_loss: 222.7552
Epoch 75/100
721/721 [==============================] - 0s 58us/step - loss: 206.3908 - val_loss: 219.5071
Epoch 76/100
721/721 [==============================] - 0s 57us/step - loss: 203.1774 - val_loss: 216.5676
Epoch 77/100
721/721 [===============

721/721 [==============================] - 0s 58us/step - loss: 606.4177 - val_loss: 580.8313
Epoch 44/100
721/721 [==============================] - 0s 60us/step - loss: 584.6267 - val_loss: 561.6202
Epoch 45/100
721/721 [==============================] - 0s 62us/step - loss: 563.2941 - val_loss: 543.3287
Epoch 46/100
721/721 [==============================] - 0s 62us/step - loss: 542.9905 - val_loss: 524.8505
Epoch 47/100
721/721 [==============================] - 0s 62us/step - loss: 522.6476 - val_loss: 506.9073
Epoch 48/100
721/721 [==============================] - 0s 61us/step - loss: 503.1157 - val_loss: 489.5556
Epoch 49/100
721/721 [==============================] - 0s 60us/step - loss: 484.5271 - val_loss: 472.2824
Epoch 50/100
721/721 [==============================] - 0s 62us/step - loss: 465.9950 - val_loss: 456.0987
Epoch 51/100
721/721 [==============================] - 0s 65us/step - loss: 448.6300 - val_loss: 439.8291
Epoch 52/100
721/721 [============================

Epoch 19/100
721/721 [==============================] - 0s 58us/step - loss: 1138.0996 - val_loss: 1034.7005
Epoch 20/100
721/721 [==============================] - 0s 57us/step - loss: 1104.7097 - val_loss: 1004.3183
Epoch 21/100
721/721 [==============================] - 0s 56us/step - loss: 1070.8786 - val_loss: 973.7119
Epoch 22/100
721/721 [==============================] - 0s 57us/step - loss: 1036.4878 - val_loss: 942.8094
Epoch 23/100
721/721 [==============================] - 0s 57us/step - loss: 1002.0305 - val_loss: 910.8182
Epoch 24/100
721/721 [==============================] - 0s 56us/step - loss: 966.5650 - val_loss: 879.7548
Epoch 25/100
721/721 [==============================] - 0s 57us/step - loss: 931.8172 - val_loss: 848.1930
Epoch 26/100
721/721 [==============================] - 0s 57us/step - loss: 896.6133 - val_loss: 816.9166
Epoch 27/100
721/721 [==============================] - 0s 57us/step - loss: 861.5616 - val_loss: 785.6982
Epoch 28/100
721/721 [========

721/721 [==============================] - 0s 62us/step - loss: 159.3349 - val_loss: 177.7148
Epoch 96/100
721/721 [==============================] - 0s 59us/step - loss: 158.3909 - val_loss: 176.9421
Epoch 97/100
721/721 [==============================] - 0s 59us/step - loss: 157.5660 - val_loss: 175.9373
Epoch 98/100
721/721 [==============================] - 0s 63us/step - loss: 156.5920 - val_loss: 175.0573
Epoch 99/100
721/721 [==============================] - 0s 59us/step - loss: 155.7109 - val_loss: 174.0826
Epoch 100/100
721/721 [==============================] - 0s 63us/step - loss: 154.7135 - val_loss: 173.2129
Sample 19
Train on 721 samples, validate on 309 samples
Epoch 1/100
721/721 [==============================] - 0s 643us/step - loss: 1597.4074 - val_loss: 1471.2887
Epoch 2/100
721/721 [==============================] - 0s 58us/step - loss: 1582.1758 - val_loss: 1456.8735
Epoch 3/100
721/721 [==============================] - 0s 57us/step - loss: 1567.1629 - val_loss:

Epoch 71/100
721/721 [==============================] - 0s 59us/step - loss: 207.3768 - val_loss: 221.7245
Epoch 72/100
721/721 [==============================] - 0s 59us/step - loss: 205.0517 - val_loss: 219.2484
Epoch 73/100
721/721 [==============================] - 0s 60us/step - loss: 202.8090 - val_loss: 216.9592
Epoch 74/100
721/721 [==============================] - 0s 58us/step - loss: 200.7037 - val_loss: 214.5598
Epoch 75/100
721/721 [==============================] - 0s 60us/step - loss: 198.5903 - val_loss: 212.5977
Epoch 76/100
721/721 [==============================] - 0s 60us/step - loss: 196.4780 - val_loss: 210.4453
Epoch 77/100
721/721 [==============================] - 0s 58us/step - loss: 194.5754 - val_loss: 208.2752
Epoch 78/100
721/721 [==============================] - 0s 61us/step - loss: 192.6466 - val_loss: 206.1612
Epoch 79/100
721/721 [==============================] - 0s 60us/step - loss: 190.8266 - val_loss: 204.3128
Epoch 80/100
721/721 [===============

721/721 [==============================] - 0s 59us/step - loss: 449.4303 - val_loss: 424.9382
Epoch 47/100
721/721 [==============================] - 0s 57us/step - loss: 426.3262 - val_loss: 405.4911
Epoch 48/100
721/721 [==============================] - 0s 58us/step - loss: 404.9034 - val_loss: 387.3055
Epoch 49/100
721/721 [==============================] - 0s 58us/step - loss: 384.9558 - val_loss: 370.4143
Epoch 50/100
721/721 [==============================] - 0s 59us/step - loss: 366.4697 - val_loss: 354.8583
Epoch 51/100
721/721 [==============================] - 0s 56us/step - loss: 349.2723 - val_loss: 340.1558
Epoch 52/100
721/721 [==============================] - 0s 57us/step - loss: 333.4355 - val_loss: 326.5017
Epoch 53/100
721/721 [==============================] - 0s 59us/step - loss: 318.8924 - val_loss: 313.9219
Epoch 54/100
721/721 [==============================] - 0s 58us/step - loss: 305.5774 - val_loss: 301.9636
Epoch 55/100
721/721 [============================

Epoch 22/100
721/721 [==============================] - 0s 57us/step - loss: 1027.5392 - val_loss: 920.8134
Epoch 23/100
721/721 [==============================] - 0s 58us/step - loss: 988.2839 - val_loss: 884.8870
Epoch 24/100
721/721 [==============================] - 0s 57us/step - loss: 948.4521 - val_loss: 849.5422
Epoch 25/100
721/721 [==============================] - 0s 56us/step - loss: 909.1825 - val_loss: 813.8626
Epoch 26/100
721/721 [==============================] - 0s 57us/step - loss: 869.3215 - val_loss: 778.7922
Epoch 27/100
721/721 [==============================] - 0s 59us/step - loss: 830.4607 - val_loss: 744.0251
Epoch 28/100
721/721 [==============================] - 0s 57us/step - loss: 792.0809 - val_loss: 709.7439
Epoch 29/100
721/721 [==============================] - 0s 60us/step - loss: 754.1094 - val_loss: 677.2542
Epoch 30/100
721/721 [==============================] - 0s 61us/step - loss: 717.9212 - val_loss: 644.9599
Epoch 31/100
721/721 [==============

721/721 [==============================] - 0s 61us/step - loss: 149.0766 - val_loss: 163.3594
Epoch 99/100
721/721 [==============================] - 0s 64us/step - loss: 148.3450 - val_loss: 162.6461
Epoch 100/100
721/721 [==============================] - 0s 59us/step - loss: 147.4051 - val_loss: 161.9335
Sample 22
Train on 721 samples, validate on 309 samples
Epoch 1/100
721/721 [==============================] - 0s 644us/step - loss: 1537.5152 - val_loss: 1410.0331
Epoch 2/100
721/721 [==============================] - 0s 58us/step - loss: 1518.5844 - val_loss: 1391.7839
Epoch 3/100
721/721 [==============================] - 0s 57us/step - loss: 1498.6080 - val_loss: 1372.8081
Epoch 4/100
721/721 [==============================] - 0s 62us/step - loss: 1477.8988 - val_loss: 1352.2238
Epoch 5/100
721/721 [==============================] - 0s 60us/step - loss: 1455.6250 - val_loss: 1331.0730
Epoch 6/100
721/721 [==============================] - 0s 59us/step - loss: 1432.3019 - val_lo

Epoch 74/100
721/721 [==============================] - 0s 64us/step - loss: 197.5217 - val_loss: 205.3135
Epoch 75/100
721/721 [==============================] - 0s 62us/step - loss: 195.0204 - val_loss: 203.0126
Epoch 76/100
721/721 [==============================] - 0s 62us/step - loss: 192.6867 - val_loss: 200.5174
Epoch 77/100
721/721 [==============================] - 0s 63us/step - loss: 190.3397 - val_loss: 198.3162
Epoch 78/100
721/721 [==============================] - 0s 60us/step - loss: 188.0520 - val_loss: 196.1481
Epoch 79/100
721/721 [==============================] - 0s 65us/step - loss: 185.9001 - val_loss: 194.1511
Epoch 80/100
721/721 [==============================] - 0s 57us/step - loss: 183.7416 - val_loss: 191.8314
Epoch 81/100
721/721 [==============================] - 0s 58us/step - loss: 181.5833 - val_loss: 189.7075
Epoch 82/100
721/721 [==============================] - 0s 58us/step - loss: 179.6314 - val_loss: 187.5770
Epoch 83/100
721/721 [===============

721/721 [==============================] - 0s 62us/step - loss: 455.7388 - val_loss: 427.5389
Epoch 50/100
721/721 [==============================] - 0s 58us/step - loss: 434.5647 - val_loss: 407.8763
Epoch 51/100
721/721 [==============================] - 0s 59us/step - loss: 413.8409 - val_loss: 389.5402
Epoch 52/100
721/721 [==============================] - 0s 58us/step - loss: 394.4034 - val_loss: 371.3146
Epoch 53/100
721/721 [==============================] - 0s 57us/step - loss: 375.6834 - val_loss: 353.7747
Epoch 54/100
721/721 [==============================] - 0s 57us/step - loss: 357.5318 - val_loss: 337.8993
Epoch 55/100
721/721 [==============================] - 0s 58us/step - loss: 340.6012 - val_loss: 322.9064
Epoch 56/100
721/721 [==============================] - 0s 57us/step - loss: 324.9409 - val_loss: 308.5625
Epoch 57/100
721/721 [==============================] - 0s 56us/step - loss: 310.0106 - val_loss: 295.6001
Epoch 58/100
721/721 [============================

Epoch 25/100
721/721 [==============================] - 0s 61us/step - loss: 948.2784 - val_loss: 860.7761
Epoch 26/100
721/721 [==============================] - 0s 56us/step - loss: 912.1817 - val_loss: 828.5581
Epoch 27/100
721/721 [==============================] - 0s 57us/step - loss: 876.8009 - val_loss: 796.0376
Epoch 28/100
721/721 [==============================] - 0s 56us/step - loss: 841.5090 - val_loss: 764.4324
Epoch 29/100
721/721 [==============================] - 0s 58us/step - loss: 807.0151 - val_loss: 733.2909
Epoch 30/100
721/721 [==============================] - 0s 56us/step - loss: 772.9770 - val_loss: 702.4552
Epoch 31/100
721/721 [==============================] - 0s 56us/step - loss: 739.8348 - val_loss: 672.2481
Epoch 32/100
721/721 [==============================] - 0s 57us/step - loss: 707.4623 - val_loss: 643.2467
Epoch 33/100
721/721 [==============================] - 0s 58us/step - loss: 676.1379 - val_loss: 615.2667
Epoch 34/100
721/721 [===============

721/721 [==============================] - 0s 623us/step - loss: 1563.5397 - val_loss: 1435.7831
Epoch 2/100
721/721 [==============================] - 0s 56us/step - loss: 1546.7751 - val_loss: 1419.7596
Epoch 3/100
721/721 [==============================] - 0s 56us/step - loss: 1529.7839 - val_loss: 1403.2275
Epoch 4/100
721/721 [==============================] - 0s 56us/step - loss: 1512.0071 - val_loss: 1385.9862
Epoch 5/100
721/721 [==============================] - 0s 57us/step - loss: 1493.3728 - val_loss: 1367.8079
Epoch 6/100
721/721 [==============================] - 0s 56us/step - loss: 1473.4684 - val_loss: 1349.2117
Epoch 7/100
721/721 [==============================] - 0s 55us/step - loss: 1453.0824 - val_loss: 1329.0193
Epoch 8/100
721/721 [==============================] - 0s 56us/step - loss: 1431.1685 - val_loss: 1307.9891
Epoch 9/100
721/721 [==============================] - 0s 56us/step - loss: 1407.9602 - val_loss: 1286.0102
Epoch 10/100
721/721 [=================

721/721 [==============================] - 0s 55us/step - loss: 170.6066 - val_loss: 186.0640
Epoch 78/100
721/721 [==============================] - 0s 57us/step - loss: 168.7861 - val_loss: 184.5463
Epoch 79/100
721/721 [==============================] - 0s 56us/step - loss: 167.0940 - val_loss: 183.0152
Epoch 80/100
721/721 [==============================] - 0s 56us/step - loss: 165.4719 - val_loss: 181.4695
Epoch 81/100
721/721 [==============================] - 0s 56us/step - loss: 163.8250 - val_loss: 180.0278
Epoch 82/100
721/721 [==============================] - 0s 56us/step - loss: 162.2571 - val_loss: 178.6773
Epoch 83/100
721/721 [==============================] - 0s 56us/step - loss: 160.8129 - val_loss: 177.2641
Epoch 84/100
721/721 [==============================] - 0s 56us/step - loss: 159.4395 - val_loss: 175.9472
Epoch 85/100
721/721 [==============================] - 0s 56us/step - loss: 157.9513 - val_loss: 174.7485
Epoch 86/100
721/721 [============================

Epoch 53/100
721/721 [==============================] - 0s 59us/step - loss: 270.9508 - val_loss: 283.1692
Epoch 54/100
721/721 [==============================] - 0s 59us/step - loss: 264.9672 - val_loss: 278.2725
Epoch 55/100
721/721 [==============================] - 0s 60us/step - loss: 259.7860 - val_loss: 273.5022
Epoch 56/100
721/721 [==============================] - 0s 58us/step - loss: 254.7276 - val_loss: 268.9844
Epoch 57/100
721/721 [==============================] - 0s 63us/step - loss: 250.2045 - val_loss: 264.7418
Epoch 58/100
721/721 [==============================] - 0s 59us/step - loss: 245.8928 - val_loss: 260.7561
Epoch 59/100
721/721 [==============================] - 0s 61us/step - loss: 241.8193 - val_loss: 257.1248
Epoch 60/100
721/721 [==============================] - 0s 59us/step - loss: 238.2346 - val_loss: 253.4527
Epoch 61/100
721/721 [==============================] - 0s 61us/step - loss: 234.6025 - val_loss: 250.1471
Epoch 62/100
721/721 [===============

721/721 [==============================] - 0s 59us/step - loss: 780.6790 - val_loss: 713.3904
Epoch 29/100
721/721 [==============================] - 0s 60us/step - loss: 743.7743 - val_loss: 680.7309
Epoch 30/100
721/721 [==============================] - 0s 60us/step - loss: 707.7115 - val_loss: 649.1583
Epoch 31/100
721/721 [==============================] - 0s 59us/step - loss: 672.8785 - val_loss: 618.2196
Epoch 32/100
721/721 [==============================] - 0s 58us/step - loss: 639.3332 - val_loss: 587.5921
Epoch 33/100
721/721 [==============================] - 0s 59us/step - loss: 606.2282 - val_loss: 558.8063
Epoch 34/100
721/721 [==============================] - 0s 62us/step - loss: 575.0724 - val_loss: 531.0601
Epoch 35/100
721/721 [==============================] - 0s 59us/step - loss: 544.9320 - val_loss: 504.5009
Epoch 36/100
721/721 [==============================] - 0s 60us/step - loss: 516.2527 - val_loss: 479.8087
Epoch 37/100
721/721 [============================

721/721 [==============================] - 0s 59us/step - loss: 1542.0044 - val_loss: 1415.8746
Epoch 5/100
721/721 [==============================] - 0s 56us/step - loss: 1526.0747 - val_loss: 1400.5148
Epoch 6/100
721/721 [==============================] - 0s 59us/step - loss: 1509.4599 - val_loss: 1384.8663
Epoch 7/100
721/721 [==============================] - 0s 57us/step - loss: 1492.3586 - val_loss: 1368.8080
Epoch 8/100
721/721 [==============================] - 0s 58us/step - loss: 1474.6073 - val_loss: 1351.8309
Epoch 9/100
721/721 [==============================] - 0s 57us/step - loss: 1455.7391 - val_loss: 1334.3578
Epoch 10/100
721/721 [==============================] - 0s 58us/step - loss: 1436.3178 - val_loss: 1315.4523
Epoch 11/100
721/721 [==============================] - 0s 57us/step - loss: 1415.2521 - val_loss: 1296.1336
Epoch 12/100
721/721 [==============================] - 0s 56us/step - loss: 1393.3697 - val_loss: 1275.0793
Epoch 13/100
721/721 [===============

721/721 [==============================] - 0s 59us/step - loss: 170.9957 - val_loss: 180.2648
Epoch 81/100
721/721 [==============================] - 0s 62us/step - loss: 169.5392 - val_loss: 179.1347
Epoch 82/100
721/721 [==============================] - 0s 59us/step - loss: 168.0911 - val_loss: 178.0523
Epoch 83/100
721/721 [==============================] - 0s 58us/step - loss: 166.8425 - val_loss: 177.0948
Epoch 84/100
721/721 [==============================] - 0s 61us/step - loss: 165.3788 - val_loss: 176.2789
Epoch 85/100
721/721 [==============================] - 0s 59us/step - loss: 164.2192 - val_loss: 175.3294
Epoch 86/100
721/721 [==============================] - 0s 60us/step - loss: 163.0417 - val_loss: 174.4598
Epoch 87/100
721/721 [==============================] - 0s 58us/step - loss: 161.8715 - val_loss: 173.6879
Epoch 88/100
721/721 [==============================] - 0s 60us/step - loss: 160.8209 - val_loss: 172.9778
Epoch 89/100
721/721 [============================

Epoch 56/100
721/721 [==============================] - 0s 56us/step - loss: 236.4677 - val_loss: 230.8850
Epoch 57/100
721/721 [==============================] - 0s 57us/step - loss: 231.1088 - val_loss: 225.9062
Epoch 58/100
721/721 [==============================] - 0s 56us/step - loss: 226.0259 - val_loss: 221.3007
Epoch 59/100
721/721 [==============================] - 0s 56us/step - loss: 221.1025 - val_loss: 217.1400
Epoch 60/100
721/721 [==============================] - 0s 57us/step - loss: 216.7488 - val_loss: 213.0568
Epoch 61/100
721/721 [==============================] - 0s 56us/step - loss: 212.5576 - val_loss: 209.4805
Epoch 62/100
721/721 [==============================] - 0s 57us/step - loss: 208.6100 - val_loss: 206.0889
Epoch 63/100
721/721 [==============================] - 0s 56us/step - loss: 204.8903 - val_loss: 202.7725
Epoch 64/100
721/721 [==============================] - 0s 56us/step - loss: 201.4436 - val_loss: 199.8579
Epoch 65/100
721/721 [===============

721/721 [==============================] - 0s 60us/step - loss: 640.1118 - val_loss: 583.7289
Epoch 32/100
721/721 [==============================] - 0s 59us/step - loss: 607.6310 - val_loss: 555.7321
Epoch 33/100
721/721 [==============================] - 0s 58us/step - loss: 576.9266 - val_loss: 528.6401
Epoch 34/100
721/721 [==============================] - 0s 57us/step - loss: 547.3656 - val_loss: 502.5599
Epoch 35/100
721/721 [==============================] - 0s 58us/step - loss: 519.1385 - val_loss: 477.9050
Epoch 36/100
721/721 [==============================] - 0s 58us/step - loss: 492.1894 - val_loss: 454.5623
Epoch 37/100
721/721 [==============================] - 0s 58us/step - loss: 467.0659 - val_loss: 432.4484
Epoch 38/100
721/721 [==============================] - 0s 59us/step - loss: 443.2099 - val_loss: 411.6232
Epoch 39/100
721/721 [==============================] - 0s 58us/step - loss: 420.7890 - val_loss: 392.3926
Epoch 40/100
721/721 [============================

721/721 [==============================] - 0s 59us/step - loss: 1561.0827 - val_loss: 1434.5128
Epoch 8/100
721/721 [==============================] - 0s 59us/step - loss: 1549.2778 - val_loss: 1423.5911
Epoch 9/100
721/721 [==============================] - 0s 65us/step - loss: 1537.6953 - val_loss: 1412.5837
Epoch 10/100
721/721 [==============================] - 0s 64us/step - loss: 1525.9570 - val_loss: 1401.4275
Epoch 11/100
721/721 [==============================] - 0s 64us/step - loss: 1514.0684 - val_loss: 1389.7812
Epoch 12/100
721/721 [==============================] - 0s 64us/step - loss: 1501.5924 - val_loss: 1377.7336
Epoch 13/100
721/721 [==============================] - 0s 64us/step - loss: 1488.6105 - val_loss: 1365.2740
Epoch 14/100
721/721 [==============================] - 0s 65us/step - loss: 1474.8874 - val_loss: 1352.5888
Epoch 15/100
721/721 [==============================] - 0s 64us/step - loss: 1460.9773 - val_loss: 1338.4303
Epoch 16/100
721/721 [============

721/721 [==============================] - 0s 62us/step - loss: 255.2709 - val_loss: 268.0788
Epoch 84/100
721/721 [==============================] - 0s 63us/step - loss: 251.5672 - val_loss: 264.8448
Epoch 85/100
721/721 [==============================] - 0s 63us/step - loss: 247.9911 - val_loss: 261.9402
Epoch 86/100
721/721 [==============================] - 0s 63us/step - loss: 244.7088 - val_loss: 258.8511
Epoch 87/100
721/721 [==============================] - 0s 64us/step - loss: 241.3828 - val_loss: 256.1759
Epoch 88/100
721/721 [==============================] - 0s 63us/step - loss: 238.2398 - val_loss: 253.4755
Epoch 89/100
721/721 [==============================] - 0s 64us/step - loss: 235.2982 - val_loss: 250.8510
Epoch 90/100
721/721 [==============================] - 0s 63us/step - loss: 232.4800 - val_loss: 248.3005
Epoch 91/100
721/721 [==============================] - 0s 62us/step - loss: 229.6313 - val_loss: 245.8288
Epoch 92/100
721/721 [============================

Epoch 59/100
721/721 [==============================] - 0s 58us/step - loss: 196.4914 - val_loss: 209.0935
Epoch 60/100
721/721 [==============================] - 0s 58us/step - loss: 193.4520 - val_loss: 206.6865
Epoch 61/100
721/721 [==============================] - 0s 57us/step - loss: 190.7439 - val_loss: 204.4204
Epoch 62/100
721/721 [==============================] - 0s 57us/step - loss: 188.2554 - val_loss: 202.2825
Epoch 63/100
721/721 [==============================] - 0s 61us/step - loss: 185.9507 - val_loss: 200.2332
Epoch 64/100
721/721 [==============================] - 0s 67us/step - loss: 183.6862 - val_loss: 198.3495
Epoch 65/100
721/721 [==============================] - 0s 67us/step - loss: 181.6365 - val_loss: 196.4978
Epoch 66/100
721/721 [==============================] - 0s 65us/step - loss: 179.6240 - val_loss: 194.8619
Epoch 67/100
721/721 [==============================] - 0s 66us/step - loss: 177.7544 - val_loss: 193.1828
Epoch 68/100
721/721 [===============

721/721 [==============================] - 0s 65us/step - loss: 935.1396 - val_loss: 851.2650
Epoch 35/100
721/721 [==============================] - 0s 64us/step - loss: 902.8734 - val_loss: 822.7807
Epoch 36/100
721/721 [==============================] - 0s 62us/step - loss: 871.1547 - val_loss: 793.7413
Epoch 37/100
721/721 [==============================] - 0s 62us/step - loss: 838.9895 - val_loss: 765.9883
Epoch 38/100
721/721 [==============================] - 0s 61us/step - loss: 807.7645 - val_loss: 738.4386
Epoch 39/100
721/721 [==============================] - 0s 63us/step - loss: 777.4037 - val_loss: 711.4645
Epoch 40/100
721/721 [==============================] - 0s 61us/step - loss: 747.4873 - val_loss: 685.1398
Epoch 41/100
721/721 [==============================] - 0s 59us/step - loss: 717.9843 - val_loss: 660.4088
Epoch 42/100
721/721 [==============================] - 0s 63us/step - loss: 690.1030 - val_loss: 635.3440
Epoch 43/100
721/721 [============================

721/721 [==============================] - 0s 60us/step - loss: 1490.8312 - val_loss: 1375.0994
Epoch 11/100
721/721 [==============================] - 0s 60us/step - loss: 1472.4340 - val_loss: 1358.5321
Epoch 12/100
721/721 [==============================] - 0s 60us/step - loss: 1453.7948 - val_loss: 1341.4971
Epoch 13/100
721/721 [==============================] - 0s 62us/step - loss: 1434.7899 - val_loss: 1324.2628
Epoch 14/100
721/721 [==============================] - 0s 67us/step - loss: 1415.1427 - val_loss: 1306.5753
Epoch 15/100
721/721 [==============================] - 0s 64us/step - loss: 1395.1407 - val_loss: 1288.4730
Epoch 16/100
721/721 [==============================] - 0s 63us/step - loss: 1374.2737 - val_loss: 1270.0401
Epoch 17/100
721/721 [==============================] - 0s 62us/step - loss: 1352.9798 - val_loss: 1251.0493
Epoch 18/100
721/721 [==============================] - 0s 62us/step - loss: 1331.0718 - val_loss: 1231.4002
Epoch 19/100
721/721 [==========

721/721 [==============================] - 0s 66us/step - loss: 237.0999 - val_loss: 257.9041
Epoch 87/100
721/721 [==============================] - 0s 65us/step - loss: 233.5128 - val_loss: 254.6194
Epoch 88/100
721/721 [==============================] - 0s 60us/step - loss: 230.0505 - val_loss: 251.4546
Epoch 89/100
721/721 [==============================] - 0s 58us/step - loss: 226.8010 - val_loss: 248.3331
Epoch 90/100
721/721 [==============================] - 0s 59us/step - loss: 223.5301 - val_loss: 245.1825
Epoch 91/100
721/721 [==============================] - 0s 57us/step - loss: 220.4094 - val_loss: 242.3466
Epoch 92/100
721/721 [==============================] - 0s 58us/step - loss: 217.4367 - val_loss: 239.4675
Epoch 93/100
721/721 [==============================] - 0s 60us/step - loss: 214.5756 - val_loss: 236.7687
Epoch 94/100
721/721 [==============================] - 0s 59us/step - loss: 211.8037 - val_loss: 234.0494
Epoch 95/100
721/721 [============================

Epoch 62/100
721/721 [==============================] - 0s 59us/step - loss: 279.0529 - val_loss: 270.7622
Epoch 63/100
721/721 [==============================] - 0s 61us/step - loss: 272.9918 - val_loss: 265.2059
Epoch 64/100
721/721 [==============================] - 0s 63us/step - loss: 267.2785 - val_loss: 259.8937
Epoch 65/100
721/721 [==============================] - 0s 62us/step - loss: 261.7116 - val_loss: 254.9214
Epoch 66/100
721/721 [==============================] - 0s 61us/step - loss: 256.7280 - val_loss: 249.9418
Epoch 67/100
721/721 [==============================] - 0s 63us/step - loss: 251.7581 - val_loss: 245.4747
Epoch 68/100
721/721 [==============================] - 0s 65us/step - loss: 247.3480 - val_loss: 241.1822
Epoch 69/100
721/721 [==============================] - 0s 62us/step - loss: 242.8288 - val_loss: 237.3476
Epoch 70/100
721/721 [==============================] - 0s 62us/step - loss: 238.8779 - val_loss: 233.3225
Epoch 71/100
721/721 [===============

721/721 [==============================] - 0s 58us/step - loss: 713.5607 - val_loss: 657.7967
Epoch 38/100
721/721 [==============================] - 0s 58us/step - loss: 680.7475 - val_loss: 628.3783
Epoch 39/100
721/721 [==============================] - 0s 58us/step - loss: 647.6286 - val_loss: 598.6494
Epoch 40/100
721/721 [==============================] - 0s 57us/step - loss: 614.5056 - val_loss: 569.5103
Epoch 41/100
721/721 [==============================] - 0s 57us/step - loss: 582.0423 - val_loss: 540.4372
Epoch 42/100
721/721 [==============================] - 0s 59us/step - loss: 550.0742 - val_loss: 511.9116
Epoch 43/100
721/721 [==============================] - 0s 57us/step - loss: 518.5440 - val_loss: 485.0073
Epoch 44/100
721/721 [==============================] - 0s 57us/step - loss: 488.7078 - val_loss: 458.7324
Epoch 45/100
721/721 [==============================] - 0s 57us/step - loss: 460.2197 - val_loss: 433.3680
Epoch 46/100
721/721 [============================

721/721 [==============================] - 0s 61us/step - loss: 1390.1288 - val_loss: 1280.1969
Epoch 14/100
721/721 [==============================] - 0s 62us/step - loss: 1362.9875 - val_loss: 1255.6112
Epoch 15/100
721/721 [==============================] - 0s 66us/step - loss: 1334.8688 - val_loss: 1230.0872
Epoch 16/100
721/721 [==============================] - 0s 62us/step - loss: 1305.6320 - val_loss: 1203.0300
Epoch 17/100
721/721 [==============================] - 0s 62us/step - loss: 1274.8407 - val_loss: 1175.0923
Epoch 18/100
721/721 [==============================] - 0s 60us/step - loss: 1243.1872 - val_loss: 1145.6477
Epoch 19/100
721/721 [==============================] - 0s 58us/step - loss: 1210.0109 - val_loss: 1116.1623
Epoch 20/100
721/721 [==============================] - 0s 58us/step - loss: 1176.7301 - val_loss: 1085.4121
Epoch 21/100
721/721 [==============================] - 0s 58us/step - loss: 1141.8178 - val_loss: 1054.8085
Epoch 22/100
721/721 [==========

721/721 [==============================] - 0s 59us/step - loss: 161.1748 - val_loss: 162.6602
Epoch 90/100
721/721 [==============================] - 0s 62us/step - loss: 159.4640 - val_loss: 161.4200
Epoch 91/100
721/721 [==============================] - 0s 63us/step - loss: 157.9415 - val_loss: 160.1569
Epoch 92/100
721/721 [==============================] - 0s 62us/step - loss: 156.4366 - val_loss: 158.9349
Epoch 93/100
721/721 [==============================] - 0s 64us/step - loss: 154.9161 - val_loss: 157.8269
Epoch 94/100
721/721 [==============================] - 0s 63us/step - loss: 153.5188 - val_loss: 156.7046
Epoch 95/100
721/721 [==============================] - 0s 59us/step - loss: 152.1954 - val_loss: 155.6482
Epoch 96/100
721/721 [==============================] - 0s 62us/step - loss: 150.8862 - val_loss: 154.7462
Epoch 97/100
721/721 [==============================] - 0s 63us/step - loss: 149.6107 - val_loss: 153.7605
Epoch 98/100
721/721 [============================

Epoch 65/100
721/721 [==============================] - 0s 59us/step - loss: 207.8757 - val_loss: 217.8574
Epoch 66/100
721/721 [==============================] - 0s 57us/step - loss: 204.0012 - val_loss: 214.4832
Epoch 67/100
721/721 [==============================] - 0s 57us/step - loss: 200.7337 - val_loss: 210.9832
Epoch 68/100
721/721 [==============================] - 0s 57us/step - loss: 197.4036 - val_loss: 208.0965
Epoch 69/100
721/721 [==============================] - 0s 57us/step - loss: 194.5518 - val_loss: 205.3737
Epoch 70/100
721/721 [==============================] - 0s 57us/step - loss: 191.9485 - val_loss: 202.8301
Epoch 71/100
721/721 [==============================] - 0s 56us/step - loss: 189.4610 - val_loss: 200.6863
Epoch 72/100
721/721 [==============================] - 0s 56us/step - loss: 187.2546 - val_loss: 198.5398
Epoch 73/100
721/721 [==============================] - 0s 57us/step - loss: 185.1368 - val_loss: 196.4709
Epoch 74/100
721/721 [===============

721/721 [==============================] - 0s 58us/step - loss: 619.2690 - val_loss: 590.8169
Epoch 41/100
721/721 [==============================] - 0s 58us/step - loss: 595.8148 - val_loss: 569.4005
Epoch 42/100
721/721 [==============================] - 0s 56us/step - loss: 572.8761 - val_loss: 549.0014
Epoch 43/100
721/721 [==============================] - 0s 58us/step - loss: 551.1913 - val_loss: 529.0757
Epoch 44/100
721/721 [==============================] - 0s 57us/step - loss: 529.9565 - val_loss: 510.3921
Epoch 45/100
721/721 [==============================] - 0s 57us/step - loss: 510.1580 - val_loss: 491.4841
Epoch 46/100
721/721 [==============================] - 0s 57us/step - loss: 490.2413 - val_loss: 473.6017
Epoch 47/100
721/721 [==============================] - 0s 58us/step - loss: 471.4346 - val_loss: 456.1774
Epoch 48/100
721/721 [==============================] - 0s 57us/step - loss: 452.9777 - val_loss: 439.3457
Epoch 49/100
721/721 [============================

Epoch 16/100
721/721 [==============================] - 0s 67us/step - loss: 1300.6277 - val_loss: 1190.8802
Epoch 17/100
721/721 [==============================] - 0s 58us/step - loss: 1274.2289 - val_loss: 1167.0607
Epoch 18/100
721/721 [==============================] - 0s 58us/step - loss: 1247.5827 - val_loss: 1141.4366
Epoch 19/100
721/721 [==============================] - 0s 58us/step - loss: 1219.4518 - val_loss: 1115.3801
Epoch 20/100
721/721 [==============================] - 0s 58us/step - loss: 1190.5994 - val_loss: 1088.4276
Epoch 21/100
721/721 [==============================] - 0s 58us/step - loss: 1161.0888 - val_loss: 1061.2588
Epoch 22/100
721/721 [==============================] - 0s 58us/step - loss: 1130.8474 - val_loss: 1033.5806
Epoch 23/100
721/721 [==============================] - 0s 61us/step - loss: 1099.8610 - val_loss: 1005.4788
Epoch 24/100
721/721 [==============================] - 0s 59us/step - loss: 1068.4229 - val_loss: 977.1138
Epoch 25/100
721/721

721/721 [==============================] - 0s 64us/step - loss: 185.9057 - val_loss: 195.0736
Epoch 93/100
721/721 [==============================] - 0s 65us/step - loss: 183.9744 - val_loss: 193.1972
Epoch 94/100
721/721 [==============================] - 0s 63us/step - loss: 182.0375 - val_loss: 191.0934
Epoch 95/100
721/721 [==============================] - 0s 63us/step - loss: 180.1665 - val_loss: 189.2741
Epoch 96/100
721/721 [==============================] - 0s 65us/step - loss: 178.3578 - val_loss: 187.4656
Epoch 97/100
721/721 [==============================] - 0s 65us/step - loss: 176.5937 - val_loss: 185.5918
Epoch 98/100
721/721 [==============================] - 0s 65us/step - loss: 174.9151 - val_loss: 184.0314
Epoch 99/100
721/721 [==============================] - 0s 63us/step - loss: 173.2442 - val_loss: 182.3220
Epoch 100/100
721/721 [==============================] - 0s 64us/step - loss: 171.6143 - val_loss: 180.6417
Sample 41
Train on 721 samples, validate on 309 s

Epoch 68/100
721/721 [==============================] - 0s 59us/step - loss: 178.8276 - val_loss: 189.8586
Epoch 69/100
721/721 [==============================] - 0s 57us/step - loss: 177.1576 - val_loss: 188.4124
Epoch 70/100
721/721 [==============================] - 0s 57us/step - loss: 175.5103 - val_loss: 187.2174
Epoch 71/100
721/721 [==============================] - 0s 57us/step - loss: 173.9815 - val_loss: 185.9459
Epoch 72/100
721/721 [==============================] - 0s 58us/step - loss: 172.5001 - val_loss: 184.8563
Epoch 73/100
721/721 [==============================] - 0s 57us/step - loss: 171.0808 - val_loss: 183.7631
Epoch 74/100
721/721 [==============================] - 0s 60us/step - loss: 169.6794 - val_loss: 182.6010
Epoch 75/100
721/721 [==============================] - 0s 58us/step - loss: 168.3238 - val_loss: 181.4350
Epoch 76/100
721/721 [==============================] - 0s 58us/step - loss: 167.0564 - val_loss: 180.5490
Epoch 77/100
721/721 [===============

721/721 [==============================] - 0s 60us/step - loss: 484.5775 - val_loss: 446.3130
Epoch 44/100
721/721 [==============================] - 0s 60us/step - loss: 464.0662 - val_loss: 427.9257
Epoch 45/100
721/721 [==============================] - 0s 58us/step - loss: 444.5283 - val_loss: 410.8652
Epoch 46/100
721/721 [==============================] - 0s 59us/step - loss: 426.1660 - val_loss: 394.8575
Epoch 47/100
721/721 [==============================] - 0s 59us/step - loss: 408.9901 - val_loss: 379.4849
Epoch 48/100
721/721 [==============================] - 0s 62us/step - loss: 392.5946 - val_loss: 365.1177
Epoch 49/100
721/721 [==============================] - 0s 62us/step - loss: 377.2064 - val_loss: 351.8994
Epoch 50/100
721/721 [==============================] - 0s 61us/step - loss: 363.0242 - val_loss: 339.0709
Epoch 51/100
721/721 [==============================] - 0s 59us/step - loss: 349.3926 - val_loss: 327.4726
Epoch 52/100
721/721 [============================

Epoch 19/100
721/721 [==============================] - 0s 62us/step - loss: 1112.6397 - val_loss: 1020.4759
Epoch 20/100
721/721 [==============================] - 0s 59us/step - loss: 1075.9581 - val_loss: 987.3244
Epoch 21/100
721/721 [==============================] - 0s 60us/step - loss: 1038.4789 - val_loss: 954.6147
Epoch 22/100
721/721 [==============================] - 0s 60us/step - loss: 1001.7353 - val_loss: 921.1519
Epoch 23/100
721/721 [==============================] - 0s 59us/step - loss: 964.2068 - val_loss: 888.2077
Epoch 24/100
721/721 [==============================] - 0s 60us/step - loss: 927.1287 - val_loss: 855.4073
Epoch 25/100
721/721 [==============================] - 0s 60us/step - loss: 890.4257 - val_loss: 822.7354
Epoch 26/100
721/721 [==============================] - 0s 59us/step - loss: 854.2228 - val_loss: 790.5898
Epoch 27/100
721/721 [==============================] - 0s 59us/step - loss: 818.4443 - val_loss: 759.4297
Epoch 28/100
721/721 [==========

721/721 [==============================] - 0s 57us/step - loss: 143.8502 - val_loss: 167.6378
Epoch 96/100
721/721 [==============================] - 0s 58us/step - loss: 142.9529 - val_loss: 166.6978
Epoch 97/100
721/721 [==============================] - 0s 57us/step - loss: 142.0306 - val_loss: 165.9629
Epoch 98/100
721/721 [==============================] - 0s 58us/step - loss: 141.0069 - val_loss: 165.0399
Epoch 99/100
721/721 [==============================] - 0s 58us/step - loss: 140.1189 - val_loss: 164.1927
Epoch 100/100
721/721 [==============================] - 0s 57us/step - loss: 139.2389 - val_loss: 163.3545
Sample 44
Train on 721 samples, validate on 309 samples
Epoch 1/100
721/721 [==============================] - 0s 618us/step - loss: 1612.1084 - val_loss: 1480.0167
Epoch 2/100
721/721 [==============================] - 0s 58us/step - loss: 1592.6364 - val_loss: 1462.1943
Epoch 3/100
721/721 [==============================] - 0s 57us/step - loss: 1573.3500 - val_loss:

721/721 [==============================] - 0s 59us/step - loss: 230.8348 - val_loss: 233.5906
Epoch 71/100
721/721 [==============================] - 0s 58us/step - loss: 226.1376 - val_loss: 229.4949
Epoch 72/100
721/721 [==============================] - 0s 56us/step - loss: 221.7279 - val_loss: 225.6360
Epoch 73/100
721/721 [==============================] - 0s 57us/step - loss: 217.5570 - val_loss: 221.9792
Epoch 74/100
721/721 [==============================] - 0s 56us/step - loss: 213.7532 - val_loss: 218.5946
Epoch 75/100
721/721 [==============================] - 0s 57us/step - loss: 210.1637 - val_loss: 215.5689
Epoch 76/100
721/721 [==============================] - 0s 56us/step - loss: 206.9443 - val_loss: 212.5662
Epoch 77/100
721/721 [==============================] - 0s 57us/step - loss: 203.7147 - val_loss: 209.9729
Epoch 78/100
721/721 [==============================] - 0s 57us/step - loss: 200.8334 - val_loss: 207.4646
Epoch 79/100
721/721 [============================

Epoch 46/100
721/721 [==============================] - 0s 61us/step - loss: 425.0981 - val_loss: 412.1762
Epoch 47/100
721/721 [==============================] - 0s 63us/step - loss: 407.4247 - val_loss: 396.6567
Epoch 48/100
721/721 [==============================] - 0s 62us/step - loss: 390.8224 - val_loss: 382.3157
Epoch 49/100
721/721 [==============================] - 0s 64us/step - loss: 375.2837 - val_loss: 368.8037
Epoch 50/100
721/721 [==============================] - 0s 63us/step - loss: 361.0699 - val_loss: 355.6257
Epoch 51/100
721/721 [==============================] - 0s 61us/step - loss: 347.2042 - val_loss: 344.1896
Epoch 52/100
721/721 [==============================] - 0s 56us/step - loss: 334.5149 - val_loss: 333.0010
Epoch 53/100
721/721 [==============================] - 0s 56us/step - loss: 322.8400 - val_loss: 322.2078
Epoch 54/100
721/721 [==============================] - 0s 57us/step - loss: 311.5836 - val_loss: 312.6364
Epoch 55/100
721/721 [===============

Epoch 22/100
721/721 [==============================] - 0s 58us/step - loss: 920.0114 - val_loss: 853.9458
Epoch 23/100
721/721 [==============================] - 0s 58us/step - loss: 881.2166 - val_loss: 819.8735
Epoch 24/100
721/721 [==============================] - 0s 57us/step - loss: 843.6143 - val_loss: 785.7321
Epoch 25/100
721/721 [==============================] - 0s 58us/step - loss: 806.1142 - val_loss: 752.1222
Epoch 26/100
721/721 [==============================] - 0s 57us/step - loss: 769.2606 - val_loss: 718.8826
Epoch 27/100
721/721 [==============================] - 0s 58us/step - loss: 733.0003 - val_loss: 686.9965
Epoch 28/100
721/721 [==============================] - 0s 60us/step - loss: 698.2483 - val_loss: 655.5633
Epoch 29/100
721/721 [==============================] - 0s 58us/step - loss: 664.2610 - val_loss: 625.6228
Epoch 30/100
721/721 [==============================] - 0s 57us/step - loss: 631.7108 - val_loss: 596.7399
Epoch 31/100
721/721 [===============

721/721 [==============================] - 0s 58us/step - loss: 150.3050 - val_loss: 160.1562
Epoch 99/100
721/721 [==============================] - 0s 58us/step - loss: 149.1604 - val_loss: 159.1992
Epoch 100/100
721/721 [==============================] - 0s 57us/step - loss: 147.7964 - val_loss: 158.0024
Sample 47
Train on 721 samples, validate on 309 samples
Epoch 1/100
721/721 [==============================] - 0s 635us/step - loss: 1629.4522 - val_loss: 1500.1773
Epoch 2/100
721/721 [==============================] - 0s 58us/step - loss: 1612.7095 - val_loss: 1484.2769
Epoch 3/100
721/721 [==============================] - 0s 58us/step - loss: 1596.0576 - val_loss: 1468.3848
Epoch 4/100
721/721 [==============================] - 0s 57us/step - loss: 1579.5881 - val_loss: 1452.0442
Epoch 5/100
721/721 [==============================] - 0s 58us/step - loss: 1562.7191 - val_loss: 1435.8920
Epoch 6/100
721/721 [==============================] - 0s 58us/step - loss: 1545.6590 - val_lo

721/721 [==============================] - 0s 66us/step - loss: 254.7779 - val_loss: 240.5622
Epoch 74/100
721/721 [==============================] - 0s 64us/step - loss: 249.2390 - val_loss: 235.9017
Epoch 75/100
721/721 [==============================] - 0s 61us/step - loss: 243.6530 - val_loss: 231.6754
Epoch 76/100
721/721 [==============================] - 0s 63us/step - loss: 238.4559 - val_loss: 227.5914
Epoch 77/100
721/721 [==============================] - 0s 67us/step - loss: 233.5733 - val_loss: 223.4688
Epoch 78/100
721/721 [==============================] - 0s 65us/step - loss: 228.8520 - val_loss: 219.8183
Epoch 79/100
721/721 [==============================] - 0s 68us/step - loss: 224.3818 - val_loss: 216.0267
Epoch 80/100
721/721 [==============================] - 0s 65us/step - loss: 220.0059 - val_loss: 212.4558
Epoch 81/100
721/721 [==============================] - 0s 63us/step - loss: 215.9317 - val_loss: 209.1716
Epoch 82/100
721/721 [============================

Epoch 49/100
721/721 [==============================] - 0s 59us/step - loss: 389.2376 - val_loss: 377.5443
Epoch 50/100
721/721 [==============================] - 0s 57us/step - loss: 376.2543 - val_loss: 365.7240
Epoch 51/100
721/721 [==============================] - 0s 58us/step - loss: 363.7254 - val_loss: 355.1498
Epoch 52/100
721/721 [==============================] - 0s 57us/step - loss: 352.1061 - val_loss: 344.7730
Epoch 53/100
721/721 [==============================] - 0s 59us/step - loss: 341.1399 - val_loss: 334.9525
Epoch 54/100
721/721 [==============================] - 0s 58us/step - loss: 330.5698 - val_loss: 325.8362
Epoch 55/100
721/721 [==============================] - 0s 57us/step - loss: 320.8756 - val_loss: 316.9685
Epoch 56/100
721/721 [==============================] - 0s 57us/step - loss: 311.4683 - val_loss: 308.7231
Epoch 57/100
721/721 [==============================] - 0s 58us/step - loss: 302.8575 - val_loss: 301.0582
Epoch 58/100
721/721 [===============

721/721 [==============================] - 0s 57us/step - loss: 1012.6342 - val_loss: 922.5586
Epoch 25/100
721/721 [==============================] - 0s 59us/step - loss: 979.3242 - val_loss: 892.3332
Epoch 26/100
721/721 [==============================] - 0s 58us/step - loss: 945.4005 - val_loss: 862.1561
Epoch 27/100
721/721 [==============================] - 0s 58us/step - loss: 911.6302 - val_loss: 831.5383
Epoch 28/100
721/721 [==============================] - 0s 57us/step - loss: 877.4223 - val_loss: 801.9440
Epoch 29/100
721/721 [==============================] - 0s 57us/step - loss: 843.9888 - val_loss: 771.7764
Epoch 30/100
721/721 [==============================] - 0s 57us/step - loss: 810.5495 - val_loss: 742.3703
Epoch 31/100
721/721 [==============================] - 0s 57us/step - loss: 777.9232 - val_loss: 713.1127
Epoch 32/100
721/721 [==============================] - 0s 57us/step - loss: 745.3481 - val_loss: 684.7414
Epoch 33/100
721/721 [===========================

721/721 [==============================] - 0s 65us/step - loss: 166.1683 - val_loss: 177.3176


In [47]:
#Calculate mean and standard deviation of RMSE list

mean = sum(eval_list) / len(eval_list) 
variance = sum([((x - mean) ** 2) for x in eval_list]) / len(eval_list) 
st_dev = variance ** 0.5


print("The Mean of the RMSE list is : " +str(mean)+ " and the Standard deviation is : " + str(st_dev)) 


The Mean of the RMSE list is : 169.60742246510526 and the Standard deviation is : 14.811519049782293


When looking at the means, we can see that by increasing the epochs from 50 to 100, we were able to decrease or RMSE form about 352 to 169!


### Experiment with More Hidden Layers

D) Based on version B) (only 50 epochs), increase the number of hidden layers to 3, each with 10 nodes, using ReLU activation functions.

In [51]:
# define regression model
def regression_model_2():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(10, activation='relu'))
    model.add(Dense(10, activation='relu'))

    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [50]:
#Establish parameters
EPochs = 50 #reseting to 50 epochs
samples = 50

In [52]:
#Predict and evaluate

#Starting list that will contain RMSE scores for each sample
eval_list = []

for i in range(samples):
    print("Sample " + str(i))
    #Split data into test and train over each iteration
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=.3, random_state=99)

    #Re-build NN
    model = regression_model_2()
    
    model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=EPochs, verbose=1)
    eval_list.append(model.evaluate(X_test, y_test, verbose=0))

    

Sample 0
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 1s 1ms/step - loss: 1582.7441 - val_loss: 1454.0802
Epoch 2/50
721/721 [==============================] - 0s 81us/step - loss: 1559.2137 - val_loss: 1428.3224
Epoch 3/50
721/721 [==============================] - 0s 86us/step - loss: 1526.1858 - val_loss: 1389.8419
Epoch 4/50
721/721 [==============================] - 0s 81us/step - loss: 1476.8210 - val_loss: 1332.2706
Epoch 5/50
721/721 [==============================] - 0s 76us/step - loss: 1401.7545 - val_loss: 1244.2844
Epoch 6/50
721/721 [==============================] - 0s 76us/step - loss: 1285.9478 - val_loss: 1111.1239
Epoch 7/50
721/721 [==============================] - 0s 75us/step - loss: 1115.1163 - val_loss: 922.4679
Epoch 8/50
721/721 [==============================] - 0s 76us/step - loss: 893.0611 - val_loss: 694.0561
Epoch 9/50
721/721 [==============================] - 0s 81us/step - loss: 645.9153 - val_los

721/721 [==============================] - 0s 76us/step - loss: 138.5222 - val_loss: 155.4409
Epoch 28/50
721/721 [==============================] - 0s 78us/step - loss: 134.3796 - val_loss: 150.9678
Epoch 29/50
721/721 [==============================] - 0s 79us/step - loss: 130.4216 - val_loss: 146.8970
Epoch 30/50
721/721 [==============================] - 0s 80us/step - loss: 126.8298 - val_loss: 142.9513
Epoch 31/50
721/721 [==============================] - 0s 87us/step - loss: 123.3081 - val_loss: 139.8226
Epoch 32/50
721/721 [==============================] - 0s 87us/step - loss: 119.8204 - val_loss: 136.8165
Epoch 33/50
721/721 [==============================] - 0s 85us/step - loss: 117.3297 - val_loss: 133.1744
Epoch 34/50
721/721 [==============================] - 0s 83us/step - loss: 113.9816 - val_loss: 129.9769
Epoch 35/50
721/721 [==============================] - 0s 86us/step - loss: 111.1837 - val_loss: 127.2784
Epoch 36/50
721/721 [==============================] - 0s 

721/721 [==============================] - 0s 73us/step - loss: 1501.4245 - val_loss: 1351.8206
Epoch 4/50
721/721 [==============================] - 0s 74us/step - loss: 1419.5789 - val_loss: 1255.9883
Epoch 5/50
721/721 [==============================] - 0s 72us/step - loss: 1292.6255 - val_loss: 1113.7485
Epoch 6/50
721/721 [==============================] - 0s 78us/step - loss: 1112.2309 - val_loss: 924.3911
Epoch 7/50
721/721 [==============================] - 0s 73us/step - loss: 884.9546 - val_loss: 702.8129
Epoch 8/50
721/721 [==============================] - 0s 76us/step - loss: 639.3781 - val_loss: 488.9737
Epoch 9/50
721/721 [==============================] - 0s 73us/step - loss: 428.0156 - val_loss: 339.4188
Epoch 10/50
721/721 [==============================] - 0s 73us/step - loss: 303.7707 - val_loss: 269.3243
Epoch 11/50
721/721 [==============================] - 0s 73us/step - loss: 251.6523 - val_loss: 245.4844
Epoch 12/50
721/721 [==============================] - 0s

Epoch 30/50
721/721 [==============================] - 0s 78us/step - loss: 135.3134 - val_loss: 152.6851
Epoch 31/50
721/721 [==============================] - 0s 78us/step - loss: 133.3652 - val_loss: 151.4069
Epoch 32/50
721/721 [==============================] - 0s 77us/step - loss: 131.5247 - val_loss: 150.2525
Epoch 33/50
721/721 [==============================] - 0s 80us/step - loss: 129.7149 - val_loss: 149.3497
Epoch 34/50
721/721 [==============================] - 0s 76us/step - loss: 128.7104 - val_loss: 148.2190
Epoch 35/50
721/721 [==============================] - 0s 78us/step - loss: 126.3205 - val_loss: 146.8942
Epoch 36/50
721/721 [==============================] - 0s 81us/step - loss: 125.3417 - val_loss: 146.1480
Epoch 37/50
721/721 [==============================] - 0s 77us/step - loss: 123.4402 - val_loss: 144.9782
Epoch 38/50
721/721 [==============================] - 0s 77us/step - loss: 122.1107 - val_loss: 144.3825
Epoch 39/50
721/721 [=========================

721/721 [==============================] - 0s 81us/step - loss: 1443.1895 - val_loss: 1289.9632
Epoch 7/50
721/721 [==============================] - 0s 77us/step - loss: 1355.3574 - val_loss: 1186.3928
Epoch 8/50
721/721 [==============================] - 0s 77us/step - loss: 1225.6315 - val_loss: 1040.1149
Epoch 9/50
721/721 [==============================] - 0s 76us/step - loss: 1047.9563 - val_loss: 854.5404
Epoch 10/50
721/721 [==============================] - 0s 76us/step - loss: 830.3634 - val_loss: 645.0398
Epoch 11/50
721/721 [==============================] - 0s 77us/step - loss: 599.6242 - val_loss: 453.0733
Epoch 12/50
721/721 [==============================] - 0s 77us/step - loss: 404.0950 - val_loss: 318.0946
Epoch 13/50
721/721 [==============================] - 0s 78us/step - loss: 283.5825 - val_loss: 258.4166
Epoch 14/50
721/721 [==============================] - 0s 76us/step - loss: 230.5875 - val_loss: 236.2453
Epoch 15/50
721/721 [==============================] -

721/721 [==============================] - 0s 83us/step - loss: 146.0504 - val_loss: 158.9198
Epoch 33/50
721/721 [==============================] - 0s 81us/step - loss: 144.6846 - val_loss: 157.7550
Epoch 34/50
721/721 [==============================] - 0s 79us/step - loss: 142.7539 - val_loss: 156.4528
Epoch 35/50
721/721 [==============================] - 0s 80us/step - loss: 141.0642 - val_loss: 155.6818
Epoch 36/50
721/721 [==============================] - 0s 77us/step - loss: 139.7773 - val_loss: 154.7457
Epoch 37/50
721/721 [==============================] - 0s 82us/step - loss: 138.2538 - val_loss: 154.5626
Epoch 38/50
721/721 [==============================] - 0s 82us/step - loss: 137.2037 - val_loss: 153.7639
Epoch 39/50
721/721 [==============================] - 0s 84us/step - loss: 136.8541 - val_loss: 152.9435
Epoch 40/50
721/721 [==============================] - 0s 79us/step - loss: 134.6382 - val_loss: 152.2413
Epoch 41/50
721/721 [==============================] - 0s 

721/721 [==============================] - 0s 82us/step - loss: 773.3877 - val_loss: 576.2716
Epoch 9/50
721/721 [==============================] - 0s 87us/step - loss: 558.1969 - val_loss: 406.9671
Epoch 10/50
721/721 [==============================] - 0s 84us/step - loss: 406.0845 - val_loss: 317.7694
Epoch 11/50
721/721 [==============================] - 0s 83us/step - loss: 322.5891 - val_loss: 269.9808
Epoch 12/50
721/721 [==============================] - 0s 79us/step - loss: 275.7120 - val_loss: 240.6084
Epoch 13/50
721/721 [==============================] - 0s 76us/step - loss: 246.0053 - val_loss: 220.8679
Epoch 14/50
721/721 [==============================] - 0s 77us/step - loss: 224.9115 - val_loss: 206.6423
Epoch 15/50
721/721 [==============================] - 0s 77us/step - loss: 208.9086 - val_loss: 196.8847
Epoch 16/50
721/721 [==============================] - 0s 79us/step - loss: 197.6758 - val_loss: 189.3673
Epoch 17/50
721/721 [==============================] - 0s 8

Epoch 35/50
721/721 [==============================] - 0s 79us/step - loss: 141.1932 - val_loss: 167.0430
Epoch 36/50
721/721 [==============================] - 0s 78us/step - loss: 139.8428 - val_loss: 165.4915
Epoch 37/50
721/721 [==============================] - 0s 78us/step - loss: 138.4882 - val_loss: 164.6225
Epoch 38/50
721/721 [==============================] - 0s 79us/step - loss: 136.9752 - val_loss: 163.3289
Epoch 39/50
721/721 [==============================] - 0s 78us/step - loss: 135.8514 - val_loss: 162.5442
Epoch 40/50
721/721 [==============================] - 0s 78us/step - loss: 135.1767 - val_loss: 161.5799
Epoch 41/50
721/721 [==============================] - 0s 77us/step - loss: 133.0472 - val_loss: 160.0026
Epoch 42/50
721/721 [==============================] - 0s 79us/step - loss: 131.9981 - val_loss: 158.8098
Epoch 43/50
721/721 [==============================] - 0s 81us/step - loss: 131.0556 - val_loss: 157.5561
Epoch 44/50
721/721 [=========================

721/721 [==============================] - 0s 83us/step - loss: 429.1798 - val_loss: 366.6122
Epoch 12/50
721/721 [==============================] - 0s 77us/step - loss: 329.7404 - val_loss: 306.2782
Epoch 13/50
721/721 [==============================] - 0s 78us/step - loss: 268.8992 - val_loss: 269.4020
Epoch 14/50
721/721 [==============================] - 0s 76us/step - loss: 230.8920 - val_loss: 245.6183
Epoch 15/50
721/721 [==============================] - 0s 76us/step - loss: 209.4626 - val_loss: 229.7687
Epoch 16/50
721/721 [==============================] - 0s 81us/step - loss: 196.1802 - val_loss: 219.2006
Epoch 17/50
721/721 [==============================] - 0s 76us/step - loss: 187.1797 - val_loss: 211.7767
Epoch 18/50
721/721 [==============================] - 0s 78us/step - loss: 180.9529 - val_loss: 206.3598
Epoch 19/50
721/721 [==============================] - 0s 78us/step - loss: 176.0298 - val_loss: 201.9313
Epoch 20/50
721/721 [==============================] - 0s 

Epoch 38/50
721/721 [==============================] - 0s 78us/step - loss: 138.3570 - val_loss: 161.5557
Epoch 39/50
721/721 [==============================] - 0s 83us/step - loss: 137.0696 - val_loss: 161.8321
Epoch 40/50
721/721 [==============================] - 0s 79us/step - loss: 136.4195 - val_loss: 160.8756
Epoch 41/50
721/721 [==============================] - 0s 77us/step - loss: 135.3065 - val_loss: 160.0187
Epoch 42/50
721/721 [==============================] - 0s 77us/step - loss: 134.4546 - val_loss: 159.7069
Epoch 43/50
721/721 [==============================] - 0s 80us/step - loss: 133.7447 - val_loss: 159.5490
Epoch 44/50
721/721 [==============================] - 0s 82us/step - loss: 132.8328 - val_loss: 158.7792
Epoch 45/50
721/721 [==============================] - 0s 80us/step - loss: 132.0736 - val_loss: 158.2868
Epoch 46/50
721/721 [==============================] - 0s 85us/step - loss: 131.7304 - val_loss: 157.7176
Epoch 47/50
721/721 [=========================

721/721 [==============================] - 0s 79us/step - loss: 200.9179 - val_loss: 218.8633
Epoch 15/50
721/721 [==============================] - 0s 76us/step - loss: 193.5401 - val_loss: 212.6144
Epoch 16/50
721/721 [==============================] - 0s 75us/step - loss: 188.0256 - val_loss: 208.0805
Epoch 17/50
721/721 [==============================] - 0s 77us/step - loss: 183.4918 - val_loss: 204.4467
Epoch 18/50
721/721 [==============================] - 0s 77us/step - loss: 178.8281 - val_loss: 199.9548
Epoch 19/50
721/721 [==============================] - 0s 75us/step - loss: 175.3019 - val_loss: 196.3844
Epoch 20/50
721/721 [==============================] - 0s 76us/step - loss: 171.5917 - val_loss: 193.4290
Epoch 21/50
721/721 [==============================] - 0s 78us/step - loss: 167.7923 - val_loss: 189.9861
Epoch 22/50
721/721 [==============================] - 0s 76us/step - loss: 164.5333 - val_loss: 187.6099
Epoch 23/50
721/721 [==============================] - 0s 

Epoch 41/50
721/721 [==============================] - 0s 80us/step - loss: 130.2486 - val_loss: 151.8251
Epoch 42/50
721/721 [==============================] - 0s 86us/step - loss: 129.1789 - val_loss: 151.1304
Epoch 43/50
721/721 [==============================] - 0s 86us/step - loss: 128.0807 - val_loss: 150.6353
Epoch 44/50
721/721 [==============================] - 0s 84us/step - loss: 127.4112 - val_loss: 149.3807
Epoch 45/50
721/721 [==============================] - 0s 83us/step - loss: 126.9082 - val_loss: 148.7231
Epoch 46/50
721/721 [==============================] - 0s 83us/step - loss: 125.6988 - val_loss: 147.6634
Epoch 47/50
721/721 [==============================] - 0s 85us/step - loss: 124.9410 - val_loss: 147.2014
Epoch 48/50
721/721 [==============================] - 0s 85us/step - loss: 123.8663 - val_loss: 146.3329
Epoch 49/50
721/721 [==============================] - 0s 83us/step - loss: 123.3823 - val_loss: 145.9561
Epoch 50/50
721/721 [=========================

721/721 [==============================] - 0s 78us/step - loss: 190.9043 - val_loss: 195.1808
Epoch 18/50
721/721 [==============================] - 0s 77us/step - loss: 183.0628 - val_loss: 190.2505
Epoch 19/50
721/721 [==============================] - 0s 78us/step - loss: 176.4345 - val_loss: 185.2488
Epoch 20/50
721/721 [==============================] - 0s 76us/step - loss: 170.8638 - val_loss: 181.9417
Epoch 21/50
721/721 [==============================] - 0s 76us/step - loss: 166.2111 - val_loss: 178.1984
Epoch 22/50
721/721 [==============================] - 0s 78us/step - loss: 161.8637 - val_loss: 175.2317
Epoch 23/50
721/721 [==============================] - 0s 77us/step - loss: 157.7323 - val_loss: 172.4350
Epoch 24/50
721/721 [==============================] - 0s 77us/step - loss: 154.3201 - val_loss: 169.7597
Epoch 25/50
721/721 [==============================] - 0s 77us/step - loss: 151.5681 - val_loss: 168.0927
Epoch 26/50
721/721 [==============================] - 0s 

Epoch 44/50
721/721 [==============================] - 0s 82us/step - loss: 108.6474 - val_loss: 118.2642
Epoch 45/50
721/721 [==============================] - 0s 77us/step - loss: 104.9581 - val_loss: 114.9349
Epoch 46/50
721/721 [==============================] - 0s 75us/step - loss: 101.9717 - val_loss: 112.1259
Epoch 47/50
721/721 [==============================] - 0s 76us/step - loss: 98.7576 - val_loss: 109.2005
Epoch 48/50
721/721 [==============================] - 0s 81us/step - loss: 95.6505 - val_loss: 106.3761
Epoch 49/50
721/721 [==============================] - 0s 88us/step - loss: 92.8843 - val_loss: 103.8382
Epoch 50/50
721/721 [==============================] - 0s 88us/step - loss: 90.1111 - val_loss: 101.0224
Sample 20
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 1s 1ms/step - loss: 1607.5581 - val_loss: 1478.0738
Epoch 2/50
721/721 [==============================] - 0s 80us/step - loss: 1594.3297 - val_loss: 146

721/721 [==============================] - 0s 87us/step - loss: 167.0561 - val_loss: 172.2941
Epoch 21/50
721/721 [==============================] - 0s 85us/step - loss: 163.4264 - val_loss: 169.6906
Epoch 22/50
721/721 [==============================] - 0s 85us/step - loss: 160.2437 - val_loss: 167.0540
Epoch 23/50
721/721 [==============================] - 0s 91us/step - loss: 157.0731 - val_loss: 164.9880
Epoch 24/50
721/721 [==============================] - 0s 99us/step - loss: 154.5921 - val_loss: 162.9988
Epoch 25/50
721/721 [==============================] - 0s 92us/step - loss: 151.7375 - val_loss: 161.8093
Epoch 26/50
721/721 [==============================] - 0s 86us/step - loss: 149.6340 - val_loss: 159.7118
Epoch 27/50
721/721 [==============================] - 0s 80us/step - loss: 147.0585 - val_loss: 158.7606
Epoch 28/50
721/721 [==============================] - 0s 83us/step - loss: 145.0115 - val_loss: 157.3626
Epoch 29/50
721/721 [==============================] - 0s 

Epoch 47/50
721/721 [==============================] - 0s 76us/step - loss: 109.4628 - val_loss: 124.5029
Epoch 48/50
721/721 [==============================] - 0s 74us/step - loss: 107.0722 - val_loss: 123.4700
Epoch 49/50
721/721 [==============================] - 0s 75us/step - loss: 105.4342 - val_loss: 121.2331
Epoch 50/50
721/721 [==============================] - 0s 76us/step - loss: 103.9613 - val_loss: 120.1628
Sample 23
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 1s 1ms/step - loss: 1596.9587 - val_loss: 1461.9783
Epoch 2/50
721/721 [==============================] - 0s 86us/step - loss: 1570.2656 - val_loss: 1431.7148
Epoch 3/50
721/721 [==============================] - 0s 83us/step - loss: 1532.7355 - val_loss: 1386.2540
Epoch 4/50
721/721 [==============================] - 0s 82us/step - loss: 1478.1482 - val_loss: 1322.8004
Epoch 5/50
721/721 [==============================] - 0s 79us/step - loss: 1402.4117 - val_lo

721/721 [==============================] - 0s 86us/step - loss: 149.2130 - val_loss: 160.0592
Epoch 24/50
721/721 [==============================] - 0s 78us/step - loss: 146.5684 - val_loss: 158.7787
Epoch 25/50
721/721 [==============================] - 0s 76us/step - loss: 144.5684 - val_loss: 157.9225
Epoch 26/50
721/721 [==============================] - 0s 79us/step - loss: 142.4094 - val_loss: 157.0466
Epoch 27/50
721/721 [==============================] - 0s 78us/step - loss: 140.7113 - val_loss: 156.1947
Epoch 28/50
721/721 [==============================] - 0s 83us/step - loss: 139.0174 - val_loss: 155.3280
Epoch 29/50
721/721 [==============================] - 0s 84us/step - loss: 137.6815 - val_loss: 155.0581
Epoch 30/50
721/721 [==============================] - 0s 82us/step - loss: 136.1255 - val_loss: 154.3182
Epoch 31/50
721/721 [==============================] - 0s 82us/step - loss: 134.5221 - val_loss: 153.4467
Epoch 32/50
721/721 [==============================] - 0s 

Epoch 50/50
721/721 [==============================] - 0s 85us/step - loss: 103.6263 - val_loss: 126.3794
Sample 26
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 1s 1ms/step - loss: 1574.5006 - val_loss: 1442.2913
Epoch 2/50
721/721 [==============================] - 0s 79us/step - loss: 1548.8960 - val_loss: 1412.2873
Epoch 3/50
721/721 [==============================] - 0s 76us/step - loss: 1510.9537 - val_loss: 1366.9151
Epoch 4/50
721/721 [==============================] - 0s 80us/step - loss: 1451.0081 - val_loss: 1293.6491
Epoch 5/50
721/721 [==============================] - 0s 77us/step - loss: 1356.5163 - val_loss: 1179.9966
Epoch 6/50
721/721 [==============================] - 0s 77us/step - loss: 1216.8475 - val_loss: 1027.9410
Epoch 7/50
721/721 [==============================] - 0s 80us/step - loss: 1039.8210 - val_loss: 854.0415
Epoch 8/50
721/721 [==============================] - 0s 77us/step - loss: 846.5308 - val_l

721/721 [==============================] - 0s 83us/step - loss: 153.8102 - val_loss: 164.9587
Epoch 27/50
721/721 [==============================] - 0s 80us/step - loss: 151.7835 - val_loss: 163.7262
Epoch 28/50
721/721 [==============================] - 0s 78us/step - loss: 149.9796 - val_loss: 162.2578
Epoch 29/50
721/721 [==============================] - 0s 76us/step - loss: 148.0748 - val_loss: 161.2621
Epoch 30/50
721/721 [==============================] - 0s 86us/step - loss: 146.5066 - val_loss: 160.7686
Epoch 31/50
721/721 [==============================] - 0s 86us/step - loss: 145.1187 - val_loss: 159.0804
Epoch 32/50
721/721 [==============================] - 0s 85us/step - loss: 143.1960 - val_loss: 158.2049
Epoch 33/50
721/721 [==============================] - 0s 85us/step - loss: 142.0391 - val_loss: 157.1029
Epoch 34/50
721/721 [==============================] - 0s 84us/step - loss: 140.7490 - val_loss: 156.0243
Epoch 35/50
721/721 [==============================] - 0s 

721/721 [==============================] - 0s 84us/step - loss: 1554.5031 - val_loss: 1424.0625
Epoch 3/50
721/721 [==============================] - 0s 87us/step - loss: 1522.3059 - val_loss: 1386.6111
Epoch 4/50
721/721 [==============================] - 0s 82us/step - loss: 1468.8716 - val_loss: 1323.3438
Epoch 5/50
721/721 [==============================] - 0s 78us/step - loss: 1378.8893 - val_loss: 1220.8823
Epoch 6/50
721/721 [==============================] - 0s 80us/step - loss: 1238.3193 - val_loss: 1064.6642
Epoch 7/50
721/721 [==============================] - 0s 78us/step - loss: 1039.8094 - val_loss: 860.2223
Epoch 8/50
721/721 [==============================] - 0s 79us/step - loss: 795.9061 - val_loss: 630.4775
Epoch 9/50
721/721 [==============================] - 0s 82us/step - loss: 547.2494 - val_loss: 429.3586
Epoch 10/50
721/721 [==============================] - 0s 84us/step - loss: 364.0048 - val_loss: 315.9234
Epoch 11/50
721/721 [==============================] -

Epoch 29/50
721/721 [==============================] - 0s 76us/step - loss: 146.5720 - val_loss: 165.5384
Epoch 30/50
721/721 [==============================] - 0s 80us/step - loss: 144.5842 - val_loss: 164.4212
Epoch 31/50
721/721 [==============================] - 0s 80us/step - loss: 142.7914 - val_loss: 163.2414
Epoch 32/50
721/721 [==============================] - 0s 80us/step - loss: 140.8617 - val_loss: 161.8213
Epoch 33/50
721/721 [==============================] - 0s 85us/step - loss: 139.4538 - val_loss: 160.3143
Epoch 34/50
721/721 [==============================] - 0s 76us/step - loss: 137.9012 - val_loss: 159.2775
Epoch 35/50
721/721 [==============================] - 0s 82us/step - loss: 136.1438 - val_loss: 158.3288
Epoch 36/50
721/721 [==============================] - 0s 78us/step - loss: 134.6238 - val_loss: 157.1753
Epoch 37/50
721/721 [==============================] - 0s 80us/step - loss: 133.1934 - val_loss: 156.0608
Epoch 38/50
721/721 [=========================

721/721 [==============================] - 0s 79us/step - loss: 1583.8110 - val_loss: 1460.7890
Epoch 6/50
721/721 [==============================] - 0s 76us/step - loss: 1577.0837 - val_loss: 1453.0052
Epoch 7/50
721/721 [==============================] - 0s 74us/step - loss: 1566.7448 - val_loss: 1440.1696
Epoch 8/50
721/721 [==============================] - 0s 76us/step - loss: 1549.3888 - val_loss: 1417.7855
Epoch 9/50
721/721 [==============================] - 0s 74us/step - loss: 1518.8322 - val_loss: 1379.1666
Epoch 10/50
721/721 [==============================] - 0s 76us/step - loss: 1464.5902 - val_loss: 1307.9210
Epoch 11/50
721/721 [==============================] - 0s 74us/step - loss: 1368.7333 - val_loss: 1194.3806
Epoch 12/50
721/721 [==============================] - 0s 76us/step - loss: 1225.5804 - val_loss: 1029.3660
Epoch 13/50
721/721 [==============================] - 0s 76us/step - loss: 1028.0035 - val_loss: 823.7971
Epoch 14/50
721/721 [========================

721/721 [==============================] - 0s 73us/step - loss: 147.3761 - val_loss: 155.4554
Epoch 32/50
721/721 [==============================] - 0s 77us/step - loss: 145.5546 - val_loss: 153.8958
Epoch 33/50
721/721 [==============================] - 0s 74us/step - loss: 143.8937 - val_loss: 153.3738
Epoch 34/50
721/721 [==============================] - 0s 73us/step - loss: 142.1624 - val_loss: 151.9449
Epoch 35/50
721/721 [==============================] - 0s 76us/step - loss: 140.5753 - val_loss: 150.9727
Epoch 36/50
721/721 [==============================] - 0s 73us/step - loss: 138.6714 - val_loss: 149.4138
Epoch 37/50
721/721 [==============================] - 0s 74us/step - loss: 137.2298 - val_loss: 147.8111
Epoch 38/50
721/721 [==============================] - 0s 76us/step - loss: 135.3985 - val_loss: 146.4656
Epoch 39/50
721/721 [==============================] - 0s 75us/step - loss: 133.9283 - val_loss: 145.4710
Epoch 40/50
721/721 [==============================] - 0s 

721/721 [==============================] - 0s 78us/step - loss: 1046.0540 - val_loss: 864.2396
Epoch 8/50
721/721 [==============================] - 0s 76us/step - loss: 831.5043 - val_loss: 658.7238
Epoch 9/50
721/721 [==============================] - 0s 78us/step - loss: 603.6905 - val_loss: 474.7385
Epoch 10/50
721/721 [==============================] - 0s 74us/step - loss: 419.9133 - val_loss: 352.9690
Epoch 11/50
721/721 [==============================] - 0s 76us/step - loss: 311.5809 - val_loss: 299.3869
Epoch 12/50
721/721 [==============================] - 0s 75us/step - loss: 263.8471 - val_loss: 269.6620
Epoch 13/50
721/721 [==============================] - 0s 74us/step - loss: 236.1985 - val_loss: 245.6302
Epoch 14/50
721/721 [==============================] - 0s 74us/step - loss: 215.1669 - val_loss: 228.0873
Epoch 15/50
721/721 [==============================] - 0s 78us/step - loss: 199.6001 - val_loss: 214.7925
Epoch 16/50
721/721 [==============================] - 0s 7

Epoch 34/50
721/721 [==============================] - 0s 79us/step - loss: 144.3453 - val_loss: 166.5761
Epoch 35/50
721/721 [==============================] - 0s 78us/step - loss: 143.0651 - val_loss: 165.5756
Epoch 36/50
721/721 [==============================] - 0s 77us/step - loss: 141.5655 - val_loss: 164.5241
Epoch 37/50
721/721 [==============================] - 0s 76us/step - loss: 139.7566 - val_loss: 163.4535
Epoch 38/50
721/721 [==============================] - 0s 77us/step - loss: 139.0460 - val_loss: 162.2026
Epoch 39/50
721/721 [==============================] - 0s 76us/step - loss: 137.5022 - val_loss: 161.1305
Epoch 40/50
721/721 [==============================] - 0s 76us/step - loss: 136.1588 - val_loss: 160.0604
Epoch 41/50
721/721 [==============================] - 0s 78us/step - loss: 135.0775 - val_loss: 159.2807
Epoch 42/50
721/721 [==============================] - 0s 75us/step - loss: 133.7462 - val_loss: 158.0553
Epoch 43/50
721/721 [=========================

721/721 [==============================] - 0s 74us/step - loss: 314.9391 - val_loss: 275.9367
Epoch 11/50
721/721 [==============================] - 0s 77us/step - loss: 248.7130 - val_loss: 247.3482
Epoch 12/50
721/721 [==============================] - 0s 77us/step - loss: 222.5263 - val_loss: 231.3034
Epoch 13/50
721/721 [==============================] - 0s 76us/step - loss: 208.0363 - val_loss: 217.6787
Epoch 14/50
721/721 [==============================] - 0s 78us/step - loss: 196.2578 - val_loss: 208.7326
Epoch 15/50
721/721 [==============================] - 0s 76us/step - loss: 188.3888 - val_loss: 201.7480
Epoch 16/50
721/721 [==============================] - 0s 76us/step - loss: 181.4896 - val_loss: 196.5446
Epoch 17/50
721/721 [==============================] - 0s 75us/step - loss: 176.6039 - val_loss: 191.8254
Epoch 18/50
721/721 [==============================] - 0s 74us/step - loss: 172.2503 - val_loss: 189.0199
Epoch 19/50
721/721 [==============================] - 0s 

Epoch 37/50
721/721 [==============================] - 0s 76us/step - loss: 119.6849 - val_loss: 141.8972
Epoch 38/50
721/721 [==============================] - 0s 78us/step - loss: 118.2131 - val_loss: 140.8089
Epoch 39/50
721/721 [==============================] - 0s 78us/step - loss: 116.7087 - val_loss: 139.0451
Epoch 40/50
721/721 [==============================] - 0s 77us/step - loss: 115.3374 - val_loss: 137.7458
Epoch 41/50
721/721 [==============================] - 0s 75us/step - loss: 113.7531 - val_loss: 136.8528
Epoch 42/50
721/721 [==============================] - 0s 85us/step - loss: 112.4118 - val_loss: 135.5747
Epoch 43/50
721/721 [==============================] - 0s 82us/step - loss: 111.3444 - val_loss: 135.3360
Epoch 44/50
721/721 [==============================] - 0s 77us/step - loss: 109.6830 - val_loss: 133.3422
Epoch 45/50
721/721 [==============================] - 0s 76us/step - loss: 108.3426 - val_loss: 132.2077
Epoch 46/50
721/721 [=========================

721/721 [==============================] - 0s 76us/step - loss: 201.1797 - val_loss: 219.5843
Epoch 14/50
721/721 [==============================] - 0s 75us/step - loss: 186.3158 - val_loss: 206.4777
Epoch 15/50
721/721 [==============================] - 0s 76us/step - loss: 176.8000 - val_loss: 197.7865
Epoch 16/50
721/721 [==============================] - 0s 76us/step - loss: 169.0160 - val_loss: 189.9320
Epoch 17/50
721/721 [==============================] - 0s 74us/step - loss: 163.7315 - val_loss: 184.7838
Epoch 18/50
721/721 [==============================] - 0s 75us/step - loss: 158.6237 - val_loss: 179.3388
Epoch 19/50
721/721 [==============================] - 0s 76us/step - loss: 154.5223 - val_loss: 175.4498
Epoch 20/50
721/721 [==============================] - 0s 76us/step - loss: 151.1607 - val_loss: 172.4737
Epoch 21/50
721/721 [==============================] - 0s 76us/step - loss: 148.1026 - val_loss: 169.2905
Epoch 22/50
721/721 [==============================] - 0s 

Epoch 40/50
721/721 [==============================] - 0s 76us/step - loss: 137.2568 - val_loss: 157.2166
Epoch 41/50
721/721 [==============================] - 0s 76us/step - loss: 136.3016 - val_loss: 156.4074
Epoch 42/50
721/721 [==============================] - 0s 77us/step - loss: 135.2997 - val_loss: 155.7496
Epoch 43/50
721/721 [==============================] - 0s 80us/step - loss: 134.0600 - val_loss: 155.0741
Epoch 44/50
721/721 [==============================] - 0s 80us/step - loss: 133.2255 - val_loss: 154.1313
Epoch 45/50
721/721 [==============================] - 0s 82us/step - loss: 132.2664 - val_loss: 152.8159
Epoch 46/50
721/721 [==============================] - 0s 77us/step - loss: 131.5108 - val_loss: 152.5035
Epoch 47/50
721/721 [==============================] - 0s 81us/step - loss: 130.6604 - val_loss: 151.6091
Epoch 48/50
721/721 [==============================] - 0s 81us/step - loss: 129.7528 - val_loss: 150.7299
Epoch 49/50
721/721 [=========================

721/721 [==============================] - 0s 77us/step - loss: 224.9518 - val_loss: 248.9757
Epoch 17/50
721/721 [==============================] - 0s 77us/step - loss: 214.4849 - val_loss: 238.6600
Epoch 18/50
721/721 [==============================] - 0s 81us/step - loss: 205.5946 - val_loss: 230.1342
Epoch 19/50
721/721 [==============================] - 0s 82us/step - loss: 198.3328 - val_loss: 222.7608
Epoch 20/50
721/721 [==============================] - 0s 78us/step - loss: 191.9527 - val_loss: 216.3358
Epoch 21/50
721/721 [==============================] - 0s 76us/step - loss: 186.7695 - val_loss: 210.7573
Epoch 22/50
721/721 [==============================] - 0s 80us/step - loss: 181.8616 - val_loss: 206.1791
Epoch 23/50
721/721 [==============================] - 0s 79us/step - loss: 177.5971 - val_loss: 201.6360
Epoch 24/50
721/721 [==============================] - 0s 77us/step - loss: 173.8171 - val_loss: 198.0133
Epoch 25/50
721/721 [==============================] - 0s 

Epoch 43/50
721/721 [==============================] - 0s 78us/step - loss: 133.0684 - val_loss: 154.9305
Epoch 44/50
721/721 [==============================] - 0s 78us/step - loss: 132.0698 - val_loss: 153.9541
Epoch 45/50
721/721 [==============================] - 0s 78us/step - loss: 130.9971 - val_loss: 153.1363
Epoch 46/50
721/721 [==============================] - 0s 76us/step - loss: 130.0708 - val_loss: 152.9088
Epoch 47/50
721/721 [==============================] - 0s 77us/step - loss: 129.1029 - val_loss: 152.2946
Epoch 48/50
721/721 [==============================] - 0s 75us/step - loss: 128.1153 - val_loss: 151.5962
Epoch 49/50
721/721 [==============================] - 0s 76us/step - loss: 127.6853 - val_loss: 150.6486
Epoch 50/50
721/721 [==============================] - 0s 79us/step - loss: 126.8546 - val_loss: 149.7260
Sample 46
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 1s 995us/step - loss: 1612.5718 - val_loss

721/721 [==============================] - 0s 75us/step - loss: 180.5321 - val_loss: 196.5363
Epoch 20/50
721/721 [==============================] - 0s 73us/step - loss: 175.9919 - val_loss: 192.7363
Epoch 21/50
721/721 [==============================] - 0s 74us/step - loss: 172.3898 - val_loss: 188.9539
Epoch 22/50
721/721 [==============================] - 0s 75us/step - loss: 168.2575 - val_loss: 185.6434
Epoch 23/50
721/721 [==============================] - 0s 80us/step - loss: 165.1758 - val_loss: 182.4655
Epoch 24/50
721/721 [==============================] - 0s 78us/step - loss: 161.5068 - val_loss: 178.9477
Epoch 25/50
721/721 [==============================] - 0s 80us/step - loss: 158.5236 - val_loss: 176.5350
Epoch 26/50
721/721 [==============================] - 0s 76us/step - loss: 155.2379 - val_loss: 173.2531
Epoch 27/50
721/721 [==============================] - 0s 77us/step - loss: 152.1418 - val_loss: 170.6785
Epoch 28/50
721/721 [==============================] - 0s 

Epoch 46/50
721/721 [==============================] - 0s 75us/step - loss: 127.5886 - val_loss: 151.2772
Epoch 47/50
721/721 [==============================] - 0s 76us/step - loss: 126.5432 - val_loss: 150.6200
Epoch 48/50
721/721 [==============================] - 0s 76us/step - loss: 125.5018 - val_loss: 149.5415
Epoch 49/50
721/721 [==============================] - 0s 76us/step - loss: 124.8743 - val_loss: 149.0439
Epoch 50/50
721/721 [==============================] - 0s 76us/step - loss: 123.9704 - val_loss: 148.4333
Sample 49
Train on 721 samples, validate on 309 samples
Epoch 1/50
721/721 [==============================] - 1s 975us/step - loss: 1593.9425 - val_loss: 1466.5379
Epoch 2/50
721/721 [==============================] - 0s 73us/step - loss: 1580.4332 - val_loss: 1452.7838
Epoch 3/50
721/721 [==============================] - 0s 72us/step - loss: 1563.0741 - val_loss: 1432.8711
Epoch 4/50
721/721 [==============================] - 0s 77us/step - loss: 1536.4124 - val_l

In [53]:
#Calculate mean and standard deviation of RMSE list

mean = sum(eval_list) / len(eval_list) 
variance = sum([((x - mean) ** 2) for x in eval_list]) / len(eval_list) 
st_dev = variance ** 0.5


print("The Mean of the RMSE list is : " +str(mean)+ " and the Standard deviation is : " + str(st_dev)) 



The Mean of the RMSE list is : 137.81916036142883 and the Standard deviation is : 15.054932603212245


When looking at the means, we can see that when we keep the same basline of B), 50 Epochs, but we increae the number of hidden layers to 3 with 10 nodes each, we were able to decrease or RMSE form about 352 to 137!


### Conclusion

After experimenting with multiple parameters and types of neural networks, it was determined that normalizing the data is a simple way to increase the performance of our models before even training them. It was also determined that 2 other ways to increase model performance are increasing the number of  epochs and the number of hidden layers. For this problem, increasing the number of hidden layers (D) to 3 yielded the best RMSE; 137.